### PR TITLE
Fix for eagerInitSingletons attempting to instantiate prototype factory methods

### LINKED ISSUE #4929: Micronaut is eagerly initialising non-singleton factory methods and parameterised beans incorrectly
## Steps to Reproduce
1. Checkout `hello-world-kotlin` project.
2. Add `.eagerInitSingletons(true)` in the bootstrap method call

## Expected Behaviour
The server starts
```
02:52:20.190 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1006ms. Server Running: http://localhost:8080
```

## Actual Behaviour
The server fails to start
```
02:53:14.202 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.grpc.ManagedChannel] could not be loaded: Error instantiating bean of type [io.grpc.ManagedChannel]: Not started
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.grpc.ManagedChannel] could not be loaded: Error instantiating bean of type [io.grpc.ManagedChannel]: Not started
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1466)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2682)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:216)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at helloworld.Application.main(Application.kt:13)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.grpc.ManagedChannel]: Not started
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1842)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2549)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2100)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1464)
	... 6 common frames omitted
Caused by: java.lang.IllegalStateException: Not started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
	at io.grpc.internal.ServerImpl.getPort(ServerImpl.java:197)
	at io.micronaut.grpc.server.GrpcEmbeddedServer.getPort(GrpcEmbeddedServer.java:123)
	at io.micronaut.grpc.server.GrpcServerChannel.serverChannel(GrpcServerChannel.java:61)
	at io.micronaut.grpc.server.$GrpcServerChannel$ServerChannel0Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1814)
	... 9 common frames omitted
````

### PR DESCRIPTION
**Pull request by jameskleeh**
Fixes #4929

### CODE REVIEW

File: core/src/main/java/io/micronaut/core/annotation/AnnotationMetadata.java [hunk 1]
```diff
@@ -225,6 +225,25 @@ default boolean hasDeclaredStereotype(@Nullable String annotation) {
...
     }
 
+    /**
+     * Checks whether this object has any of the given stereotype directly declared on the object.
+     *
+     * @param annotations The annotations
+     * @return True if any of the given stereotypes are present
+     */
+    @SuppressWarnings("unchecked")
+    default boolean hasDeclaredStereotype(@Nullable String... annotations) {
```
Comment (graemerocher) [inline core/src/main/java/io/micronaut/core/annotation/AnnotationMetadata.java:236]: Needs `@since` with the version

**Review by graemerocher — CHANGES_REQUESTED** [review]
Only one small change
