### PR TITLE
Jaeger tracer to capture http details of server error responses

### LINKED ISSUE #4111: Http status_code missing from Jaeger server span for error responses
### Steps to Reproduce

1. Enable Jaeger tracer in your Micronaut application
2. Call an HTTP endpoint where the controller method throws an exception
3. An error response is returned

### Expected Behaviour

The server span of the request should capture the status_code of the returned HTTP response, similarly as it happens in case of a OK response. Note: this works perfectly with Brave tracer.

### Actual Behaviour

Http status_code is missing from the recorded span.

### Environment Information

- **Operating System**: macOS 10.15.6
- **Micronaut Version:** 2.0.2
- **JDK Version:** 11.0.8

### Example Application

I modified the existing Jaeger related `HttpTracingSpec` tests to reflect the expected behaviour in this [branch](https://github.com/Tesco/micronaut-core/tree/trace-http-details-of-error-responses), see: [diff](https://github.com/Tesco/micronaut-core/commit/4e221d9aa2deb19c8e8d98be57fe539d77316e61#diff-09479b726a409e9d167a7fbb90f6485f)
I also found a potential solution to resolve it, I will raise a PR.

### PR DESCRIPTION
**Pull request by lgathy**
Closes #4111

### CODE REVIEW

File: tracing/src/main/java/io/micronaut/tracing/instrument/util/TracingPublisher.java [hunk 1]
```diff
@@ -193,6 +193,25 @@ public void onComplete() {
         }
     }
 
+    /**
+     * Designed for subclasses to override if the current active span is to be continued by this publisher. False by default.
+     * This only has effects if no spanBuilder was defined.
+     *
+     * @return true, if the current span should be continued by this publisher
+     */
+    protected boolean isContinued() {
```
Comment (graemerocher) [inline tracing/src/main/java/io/micronaut/tracing/instrument/util/TracingPublisher.java:203]: Please add `@since` with 2.0.3 as the version

File: tracing/src/main/java/io/micronaut/tracing/instrument/util/TracingPublisher.java [hunk 2]
```diff
@@ -193,6 +193,25 @@ public void onComplete() {
...
+        return false;
+    }
+
+    /**
+     * Designed for subclasses to override if the span needs to be finished upon error. True by default.
+     *
+     * @return true, if the active span needs to be finished on error
+     */
+    protected boolean isFinishOnError() {
```
Comment (graemerocher) [inline tracing/src/main/java/io/micronaut/tracing/instrument/util/TracingPublisher.java:213]: Please add `@since` with 2.0.3 as the version

**Review by graemerocher — CHANGES_REQUESTED** [review]
Couple of minor javadoc changes. Thanks

**Review by graemerocher — APPROVED** [review]

**Comment by graemerocher** [comment]
Thanks for the contribution!
