### PR TITLE
Fix aop/executable methods with multidimensional arrays

### LINKED ISSUE #4709: Bridge method generator fails when mutli-dimension array is used
2.2.1

Steps to reproduce:
Modify existing test bean:
```
@ProxyIntroduction
@ProxyAround
public class MyBean1 {
...
    public void list(String[][] multidim) {
    }
...
}
```
Run `io.micronaut.aop.introduction.with_around.IntroductionWithAroundOnConcreteClassSpec`

Error:
```
Caused by: java.lang.UnsupportedOperationException
	at org.objectweb.asm.Type.getOpcode(Type.java:802)
	at org.objectweb.asm.commons.GeneratorAdapter.loadInsn(GeneratorAdapter.java:481)
	at org.objectweb.asm.commons.GeneratorAdapter.loadArg(GeneratorAdapter.java:508)
	at io.micronaut.aop.writer.AopProxyWriter.visitAroundMethod(AopProxyWriter.java:554)
	at io.micronaut.aop.writer.AopProxyWriter.visitAroundMethod(AopProxyWriter.java:496)
	at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor$AnnBeanElementVisitor$1.accept(BeanDefinitionInjectProcessor.java:729)
```

Not sure what is wrong, I have tried to upgrade ASM but it didn't help.

### PR DESCRIPTION
**Pull request by jameskleeh**
Fixes #4709

### CODE REVIEW

File: inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java [hunk 1]
```diff
@@ -2245,15 +2245,14 @@ private ExecutableElementParamInfo populateParameterData(@Nullable String declar
...
                         Object resolvedType = modelUtils.resolveTypeReference(arrayType);
                         params.addParameter(
                                 argName,
                                 resolvedType,
                                 genericUtils.resolveTypeReference(arrayType, boundTypes)
                         );
-                        params.addGenericTypes(argName, Collections.singletonMap("E", modelUtils.resolveTypeReference(componentType)));
-
+                        //TypeMirror componentType = arrayType.getComponentType();
+                        //params.addGenericTypes(argName, Collections.singletonMap("E", modelUtils.resolveTypeReference(componentType)));
```
Comment (jameskleeh) [inline inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java:2255]: @graemerocher I couldn't understand why arrays were given a static generic E. It didn't make sense to me so I commented it out.

**Comment by graemerocher** [comment]
I am currently working towards a major refactor in the 2.3.x branch for type annotation support which may address this issue. I am concerned about merging this as it may be significantly complicated to merge afterwards
