### PR TITLE
Change SimpleHttpHeaders implementation to use multimap

### LINKED ISSUE #4126: SimpleHttpHeaders.add() is setting the header instead of adding
[This line](https://github.com/micronaut-projects/micronaut-core/blob/master/http/src/main/java/io/micronaut/http/simple/SimpleHttpHeaders.java#L90) is **setting** the header instead of **adding** a new header value. The entire implementation looks wrong as well, because Http headers can accept multi values..

I have found it by chance while running unit tests in a project without `micronaut-http-server-netty`. If netty project is added, calls to `io.micronaut.http.HttpResponse.ok()` would return a netty implementation at low level that doesn`t have the bug.

### PR DESCRIPTION
**Pull request by ze12augusto**
Fix #4126

### CODE REVIEW

File: http/src/main/java/io/micronaut/http/simple/SimpleHttpHeaders.java [hunk 1]
```diff
@@ -53,31 +56,26 @@ public SimpleHttpHeaders(ConversionService conversionService) {
     @Override
     @SuppressWarnings("unchecked")
     public <T> Optional<T> get(CharSequence name, ArgumentConversionContext<T> conversionContext) {
-        String value = headers.get(name.toString());
-        if (value != null) {
+        Optional<String> value = headers.getFirst(name.toString());
+        if (value.isPresent()) {
             return conversionService.convert(value, conversionContext);
         }
         return Optional.empty();
```
Comment (jameskleeh) [inline http/src/main/java/io/micronaut/http/simple/SimpleHttpHeaders.java]: This can be changed to use `.map()`

**Review by jameskleeh — CHANGES_REQUESTED** [review]

**Comment by graemerocher** [comment]
Thanks for the contribution!
