### PR TITLE
Access log can exclude defined regular expression patterns

### LINKED ISSUE #4653: Disable access logger for management endpoints
Access Logging described here: https://docs.micronaut.io/latest/guide/index.html#accessLogger is turned on for both management and regular HTTP endpoints. For services that have scrapers that hit the health / info endpoints this introduces a lot of logging and it'd be ideal to disable those logs.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

* Turn on access logging with instructions in the docs: https://docs.micronaut.io/latest/guide/index.html#accessLogger
* Send request to any management endpoint

### Expected Behaviour

* There should be a flag for disabling logging for management endpoints

### Actual Behaviour

* Expected behavior doesn't exist

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** TODO
- **JDK Version:** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

### PR DESCRIPTION
**Pull request by timyates**
This change allows the user to specify a list of regular expression patterns that are compiled
and matched against the current request URI.

If the request URI matches one of them, then the request does not appear in the access log.

### CODE REVIEW

File: http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java [hunk 1]
```diff
@@ -50,11 +52,17 @@
      */
     public static final String HTTP_ACCESS_LOGGER = "HTTP_ACCESS_LOGGER";
 
+    /**
+     * A lenient filter that allows all uri's to pass.
+     */
+    public static final Predicate<String> INCLUDE_ALL = uri -> true;
```
Comment (graemerocher) [inline http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java]: Perhaps use `null` as the value for `INCLUDE_ALL` as it will add a little less overhead

**Review by graemerocher — CHANGES_REQUESTED** [review]

File: http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java (hunk 1 above)
Comment (timyates) [reply http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java]: Good shout.  Done 👍

File: http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java [hunk 2]
```diff
@@ -73,25 +87,42 @@ public HttpAccessLogHandler(String loggerName, String spec) {
...
+                String protocol;
+                if (headers.contains(ExtensionHeaderNames.STREAM_ID.text()) || headers.contains(ExtensionHeaderNames.SCHEME.text())) {
+                    protocol = H2_PROTOCOL_NAME;
+                } else {
+                    protocol = request.protocolVersion().text();
+                }
+                accessLog.onRequestHeaders(channel, request.method().name(), request.headers(), request.uri(), protocol);
             } else {
-                protocol = request.protocolVersion().text();
+                accessLog.exclude();
```
Comment (jameskleeh) [inline http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java:124]: @graemerocher Would it be safe here to remove the handler from the pipeline? Setting an excluded flag and checking it is extra overhead

Comment (timyates) [reply http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java:124]: Nice idea!

```
                ctx.pipeline().remove(this);
```

Seems to work in the test...  Checking, and if there's no issues I can find I'll push

Comment (timyates) [reply http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java:124]: Load tested it with a filtered url and a non-filtered url

```
ab -k -n 100000 -r -c 5 http://localhost:8080/path/one & ab -k -r -n 100000 -c 5 http://localhost:8080/something
```

And we didn't get any errors.  I'm not a Netty-guru (yet) though, so @graemerocher may know if this is a dangerous thing to be doing

Anyway, pushed the change 👍

Comment (timyates) [reply http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java:124]: Right, so that doesn't work with keep-alive connections (all logs get dropped after the first excluded one removes the handler from the pipeline)

Reverted back to the field

File: http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java [hunk 3]
```diff
@@ -55,6 +57,7 @@
 
     private final Logger logger;
     private final AccessLogFormatParser accessLogFormatParser;
+    private final Predicate<String> uriInclusion;
```
Comment (yawkat) [inline http-server-netty/src/main/java/io/micronaut/http/server/netty/handler/accesslog/HttpAccessLogHandler.java:60]: `@Nullable`

**Review by yawkat — APPROVED** [review]

**Comment by yawkat** [comment]
@jameskleeh can you merge this before monday so i can fix up #6785 in time for 3.3?

**Comment by jameskleeh** [comment]
@yawkat Yeah I wasn't sure if you wanted to make the edits on this PR or not. If you're good with it I'll merge

**Comment by yawkat** [comment]
@jameskleeh i don't have any changes to make to this PR. I've put them all in #6785, because they're unrelated to the exclusions feature.
