### PR TITLE
Do not try to apply JsonView to failed responses

### LINKED ISSUE #9975: JsonView with ExceptionHandler throws 500 error in 4.1.2
### Expected Behavior

I call a rest method with the @JsonView annotation. The method throws an error. The error gets handled by my error handler and returns the appropriate response status and body.

### Actual Behaviour

Instead of my handled error response being returned I get a 500 error instead. In the logs I see an exception is thrown saying that the the JsonError is incompatible with the expected return type.

```
09:07:08.770 [io-executor-thread-3] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error encoding object [Not Found] to JSON: Incompatible types: declared root type ([simple type, class test_email_validation.MyObj]) vs `io.micronaut.http.hateoas.JsonError`
io.micronaut.http.codec.CodecException: Error encoding object [Not Found] to JSON: Incompatible types: declared root type ([simple type, class test_email_validation.MyObj]) vs `io.micronaut.http.hateoas.JsonError`
	at io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:268)
	at io.micronaut.http.server.netty.jackson.JsonViewServerFilter.lambda$doFilter$1(JsonViewServerFilter.java:99)
	at reactor.core.publisher.MonoCallable.call(MonoCallable.java:72)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:227)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$4(PropagatedContext.java:228)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$4(PropagatedContext.java:228)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Incompatible types: declared root type ([simple type, class test_email_validation.MyObj]) vs `io.micronaut.http.hateoas.JsonError`
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1308)
	at com.fasterxml.jackson.databind.SerializerProvider._reportIncompatibleRootType(SerializerProvider.java:1399)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:380)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1568)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1273)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsBytes(ObjectWriter.java:1163)
	at io.micronaut.jackson.databind.JacksonDatabindMapper.writeValueAsBytes(JacksonDatabindMapper.java:209)
	at io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:265)
	... 12 common frames omitted
```

### Steps To Reproduce

1.  Create a GET rest endpoint
2. Annotate rest endpoint with JSON view and the appropriate view class
3. rest endpoint should declare a return type other than void.
4. Throw a custom exception
5. Create a ExceptionHandler for the custom exception
6. ExceptionHandler should generate a response with a body of type JsonError.
7. Startup the application, hit the endpoint that throws the custom exception. This should result in a 500 error because JsonError is not of the same type as the rest endpoint return type.

### Environment Information

- Mac
- Java 17
- Maven 3.9.4
- Micronaut 4.1.2

### Example Application

https://github.com/kevind-wgu/micronaut-jsonview-bug

### Version

4.1.2

### PR DESCRIPTION
**Pull request by yawkat**
As the failed response contains a body not returned by the controller method, don't try to apply the controller's JsonView to it.

Fixes #9975

### CODE REVIEW

File: http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java [hunk 1]
```diff
@@ -84,7 +84,10 @@ public final Publisher<? extends MutableHttpResponse<?>> doFilter(HttpRequest<?>
         if (routeInfo != null) {
             final Optional<Class<?>> viewClass = routeInfo.findAnnotation(JsonView.class)
                 .flatMap(AnnotationValue::classValue);
-            if (viewClass.isPresent()) {
+            if (viewClass.isPresent() &&
+                // if this is an error response, the response body does not come from the controller
+                response.getAttribute(HttpAttributes.EXCEPTION).isEmpty()) {
```
Comment (graemerocher) [inline http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java]: `!response.getAttributes().contains(HttpAttributes.EXCEPTION)` will perform better

**Review by graemerocher — APPROVED** [review]

File: http-server-netty/src/test/groovy/io/micronaut/http/server/netty/jackson/JsonViewServerFilterSpec.groovy [hunk 2]
```diff
@@ -126,4 +128,20 @@ class JsonViewServerFilterSpec extends Specification {
...
+
+        then:
+        def f = thrown HttpClientResponseException
+        f.response.getBody(JsonError).get().message == "Internal Server Error"
+
+        when:
+        client.toBlocking().exchange(HttpRequest.GET('/jsonview/failing-with-route'), TestModel)
+
+        then:
+        def e = thrown HttpClientResponseException
```
Comment (sdelamo) [inline http-server-netty/src/test/groovy/io/micronaut/http/server/netty/jackson/JsonViewServerFilterSpec.groovy]:
```suggestion
        HttpClientResponseException e = thrown()
```

File: http-server-netty/src/test/groovy/io/micronaut/http/server/netty/jackson/JsonViewServerFilterSpec.groovy [hunk 3]
```diff
@@ -126,4 +128,20 @@ class JsonViewServerFilterSpec extends Specification {
...
+    def "errors are written properly"() {
+        when:
+        client.toBlocking().exchange(HttpRequest.GET('/jsonview/failing'), TestModel)
+
+        then:
+        def f = thrown HttpClientResponseException
+        f.response.getBody(JsonError).get().message == "Internal Server Error"
+
+        when:
+        client.toBlocking().exchange(HttpRequest.GET('/jsonview/failing-with-route'), TestModel)
```
Comment (sdelamo) [inline http-server-netty/src/test/groovy/io/micronaut/http/server/netty/jackson/JsonViewServerFilterSpec.groovy]:
```suggestion
        client.toBlocking().exchange(HttpRequest.GET('/jsonview/failing-with-route'))
```

**Review by sdelamo — APPROVED** [review]

File: http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java (hunk 1 above)
Comment (yawkat) [reply http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java]:
```suggestion
                !response.getAttributes().contains(HttpAttributes.EXCEPTION)) {
```

**Comment by sdelamo** [comment]
CI failed with 
> Task :http-server-netty:compileJava FAILED

File: http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java [hunk 4]
```diff
@@ -84,7 +84,10 @@ public final Publisher<? extends MutableHttpResponse<?>> doFilter(HttpRequest<?>
         if (routeInfo != null) {
             final Optional<Class<?>> viewClass = routeInfo.findAnnotation(JsonView.class)
                 .flatMap(AnnotationValue::classValue);
-            if (viewClass.isPresent()) {
+            if (viewClass.isPresent() &&
+                // if this is an error response, the response body does not come from the controller
+                !response.getAttributes().contains(HttpAttributes.EXCEPTION)) {
```
Comment (yawkat) [inline http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonViewServerFilter.java]:
```suggestion
                !response.getAttributes().contains(HttpAttributes.EXCEPTION.toString())) {
```
