### PR TITLE
Correct bootstrap env detection

### LINKED ISSUE #6226: bootstrap.yaml not recognized
### Expected Behavior

whatever the file extension name (yaml or yml), the file should be loaded

### Actual Behaviour

When the bootstrap file extension is **yaml**, it is not recognized and so not loaded when starting app

### Steps To Reproduce

1. Create a simple micronaut project
2. add a _bootstrap.yml_ file
3. launch the app and see that the file is recognized

> [main] INFO  i.m.context.DefaultBeanContext - Reading Startup environment from bootstrap.yml

4. rename the file from _bootstrap.yml_ to _bootstrap.yaml_
5. see that the bootstrap is not taken into account

### Environment Information

- Operating System: MacOS
- Micronaut Version: 3.0.1
- JDK Version: 11
- gradle 7.2
- micronaut-gradle-plugin 2.0.4 

### Example Application

_No response_

### Version

3.0.1

### PR DESCRIPTION
**Pull request by dstepanov**
Alternative solution for https://github.com/micronaut-projects/micronaut-core/pull/6234

### CODE REVIEW

File: inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java [hunk 1]
```diff
@@ -103,57 +114,49 @@ public ClassLoader getClassLoader() {
...
+    private boolean isBootstrapEnabled(ApplicationContextConfiguration configuration) {
+        Boolean configBootstrapEnabled = configuration.isBootstrapEnvironmentEnabled();
+        String bootstrapContextProp = System.getProperty(Environment.BOOTSTRAP_CONTEXT_PROPERTY);
+        Boolean systemBootstrapEnabled = bootstrapContextProp == null ? null : Boolean.parseBoolean(bootstrapContextProp);
+        if (systemBootstrapEnabled == Boolean.FALSE) {
+            return false;
+        }
+        if (systemBootstrapEnabled == Boolean.TRUE) {
+            return true;
+        }
```
Comment (burtbeckwith) [inline inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java]:
```suggestion
        if (systemBootstrapEnabled != null) {
            return systemBootstrapEnabled;
        }
```

File: inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java [hunk 2]
```diff
@@ -712,18 +715,29 @@ public Environment stop() {
...
+            if (bootstrapEnvironment == null && bootstrapEnabled) {
+
+                String bootstrapContextProp = System.getProperty(Environment.BOOTSTRAP_CONTEXT_PROPERTY);
+                boolean forceBootstrap = bootstrapContextProp != null && Boolean.parseBoolean(bootstrapContextProp) == Boolean.TRUE;
+
+                BootstrapEnvironment bootstrapEnv = createBootstrapEnvironment(getActiveNames().toArray(new String[0]));
+                if (forceBootstrap || CollectionUtils.isNotEmpty(bootstrapEnv.readPropertySourceList(bootstrapEnv.getPropertySourceRootName()))) {
+                    bootstrapEnvironment = startBootstrapEnvironment(bootstrapEnv);
+                } else {
+                    if (LOG.isInfoEnabled()) {
```
Comment (burtbeckwith) [inline inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java]: no need for enabled check

**Review by graemerocher — APPROVED** [review]
