### PR TITLE
Fix lifecycle of HttpClient and BlockingHttpClient

### LINKED ISSUE #11307: Closed HTTP client reports incorrect error on request
### Issue description

It reports 'Cannot send HTTPS request. SSL is disabled' when it should be a specific error

### PR DESCRIPTION
**Pull request by glorrian**
#### Fix a bug  when a closed client issued an incorrect error as mentioned in #11307
Add special exceptions to simple requests and web sockets
Make tests for it
#### Add Lifecycle to the BlockingHttpClient interface as well as HttpClient interface
Implement new methods at BlockingHttpClient anonymous class at DefaultHttpClient
Implement new methods at JdkBlockingHttpClient
#### Fix tests where an undisclosed client was used
  JsonStreamSpec: delete "cleanup" with closing clients on each test since the client is shared between all tests and closes automatically at the end(@AutoClosable)
  HttpHeadSpec: replace "close" with "refresh" in "cleanup" of one test cause this instance of client is used by other tests
  ClientHostNameSpec: replace "close" with "refresh" in "cleanup" of one test cause HttpClient.create() caching clients instances so actually all tests use one instance of client
  ByteBufferSpec: make client field @Shared cause @Inject fields caching so all test actually use one instance of client

### CODE REVIEW

File: http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java [hunk 1]
```diff
@@ -193,6 +193,8 @@ public class ConnectionManager {
         this.clientCustomizer = from.clientCustomizer;
         this.informationalServiceId = from.informationalServiceId;
         this.nettyClientSslBuilder = from.nettyClientSslBuilder;
+
+        refresh();
```
Comment (yawkat) [inline http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java]: I don't think this is necessary

File: http-client/src/test/groovy/io/micronaut/http/client/ClientHostNameSpec.groovy [hunk 2]
```diff
@@ -15,7 +15,7 @@ class ClientHostNameSpec extends Specification {
         e.message.contains('Connect Error: foo_bar') || e.message.contains('Connect Error: No such host is known (foo_bar)')
 
         cleanup:
-        client.close()
+        client.refresh()
```
Comment (yawkat) [inline http-client/src/test/groovy/io/micronaut/http/client/ClientHostNameSpec.groovy]: why these changes?

File: http-client/src/test/groovy/io/micronaut/http/client/HttpHeadSpec.groovy [hunk 3]
```diff
@@ -364,7 +364,7 @@ class HttpHeadSpec extends Specification {
         body == "success"
 
         cleanup:
-        client.close()
+        client.refresh()
```
Comment (yawkat) [inline http-client/src/test/groovy/io/micronaut/http/client/HttpHeadSpec.groovy:367]: this one too

File: http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java (hunk 1 above)
Comment (glorrian) [reply http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java]: This is necessary cause this constructor is used for copying ConnectionManager to new instance so we need to bootstrap new instance to setup states. For example AtomicBoolean running is false by default and without refresh() isRunning() will return false. I add this line cause i had failed tests. Hope you will get me, thanks for your review.

File: http-client/src/test/groovy/io/micronaut/http/client/ClientHostNameSpec.groovy (hunk 2 above)
Comment (glorrian) [reply http-client/src/test/groovy/io/micronaut/http/client/ClientHostNameSpec.groovy]: Cause if close this instance other tests will get an already closed client and then throw an exception when trying to use it

File: http-client/src/test/groovy/io/micronaut/http/client/HttpHeadSpec.groovy (hunk 3 above)
Comment (glorrian) [reply http-client/src/test/groovy/io/micronaut/http/client/HttpHeadSpec.groovy:367]: Same as previous comment

File: http-client/src/test/groovy/io/micronaut/http/client/ClientHostNameSpec.groovy (hunk 2 above)
Comment (yawkat) [reply http-client/src/test/groovy/io/micronaut/http/client/ClientHostNameSpec.groovy]: the client in this test is not shared

Comment (glorrian) [reply http-client/src/test/groovy/io/micronaut/http/client/ClientHostNameSpec.groovy]: Not shared but cached inside factory i guess. When trying to run these tests, I get “closed client” exceptions, when I replace them with refresh, all the tests actually pass. I made quick look up inside the impl of factory client method, and it seems to me that this is caching code, but maybe I'm wrong. I'll check it again and come back with a final answer.

Comment (glorrian) [reply http-client/src/test/groovy/io/micronaut/http/client/ClientHostNameSpec.groovy]: You're right! these tests failed because of the vpn on my mac. I removed refresh() in this spec.

File: http-client/src/test/groovy/io/micronaut/http/client/HttpHeadSpec.groovy (hunk 3 above)
Comment (glorrian) [reply http-client/src/test/groovy/io/micronaut/http/client/HttpHeadSpec.groovy:367]: this one actually use one shared instance by hashCode
Screenshot 2024-11-07 at 23 46 33 copy

**Comment by glorrian** [comment]
@graemerocher @yawkat can you restart build? I think this one failed test is flaky cause it passed on 21 java and on all my local environments

**Comment by yawkat** [comment]
Thanks!
