### PR TITLE
Fix full response body logging

### LINKED ISSUE #7572: HttpClient regressions: response payload is no logger logged when TRACE enabled
### Expected Behavior

The `DefaultHttpClient` is no longer logging the response payload.

Prior the @yawkat 's change https://github.com/micronaut-projects/micronaut-core/commit/18ef607c4c6ec276b2e0163f27cf4e28fce96b01 

when enabled trace logging in `http-client/src/test/resources/logback.xml` 
```
  <logger name="io.micronaut.http.client" level="TRACE" />
```
the Micronaut test `http-client/src/test/groovy/io/micronaut/http/client/HttpGetSpec.groovy` (and all the other tests or production code) used to log (for example when running `test get with @Client` test method)
```
14:52:16.273 [default-nioEventLoopGroup-1-2] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 200 from http://localhost:62676/get/queryParam?foo=a!b
...
14:52:16.273 [default-nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - Response Body
14:52:16.273 [default-nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
14:52:16.273 [default-nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - a!b
14:52:16.273 [default-nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
... 
```

### Actual Behaviour

After that change, Micronaut skips logging the response payload completely:
```
15:00:18.681 [default-nioEventLoopGroup-1-10] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 200 from http://localhost:63089/get/queryParam?foo=a!b
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - HTTP Client Streaming Response Received (200 OK) for Request: GET http://localhost:63089/get/queryParam?foo=a!b
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - date: Mon, 13 Jun 2022 13:00:18 GMT
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - Content-Type: application/json
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - connection: close
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - content-length: 3
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - [id: 0x1563a4f3, L:/127.0.0.1:63094 - R:localhost/127.0.0.1:63089] CLOSE
```

I also noticed there is a new log statement `HTTP Client Streaming Response Received (200 OK)` which is there even when nothing is being streamed as far as a user can tell (using blocking client with `Controller` returning a non-reactive type).

### Steps To Reproduce

Execute `io.micronaut.http.client.HttpGetSpec#test get with @Client` test
with `TRACE` logging enabled.

### Environment Information

_No response_

### Example Application

_No response_

### Version

3.5.1

### PR DESCRIPTION
**Pull request by yawkat**
In 18ef607c4c6ec276b2e0163f27cf4e28fce96b01, I merged the code paths of the full response and streaming response handlers. I included the chunk-level logging for the streaming response, but missed the full response logging.
Fixes #7572

### CODE REVIEW

File: http-client/src/test/groovy/io/micronaut/http/client/HttpClientTraceLoggingSpec.groovy [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+        appender.events.any { it.contains('foo') }
+
+        cleanup:
+        client.close()
+        server.stop()
+        ctx.stop()
+    }
+
+
+    static class MemoryAppender extends AppenderBase<ILoggingEvent> {
```
Comment (timyates) [inline http-client/src/test/groovy/io/micronaut/http/client/HttpClientTraceLoggingSpec.groovy]: Instead of writing a MemoryAppender, we could use the ListAppender that comes with logback:

```diff
diff --git a/http-client/src/test/groovy/io/micronaut/http/client/HttpClientTraceLoggingSpec.groovy b/http-client/src/test/groovy/io/micronaut/http/client/HttpClientTraceLoggingSpec.groovy
index 28825d6348..1fdd470b0e 100644
--- a/http-client/src/test/groovy/io/micronaut/http/client/HttpClientTraceLoggingSpec.groovy
+++ b/http-client/src/test/groovy/io/micronaut/http/client/HttpClientTraceLoggingSpec.groovy
@@ -3,7 +3,7 @@ package io.micronaut.http.client
 import ch.qos.logback.classic.Level
 import ch.qos.logback.classic.Logger
 import ch.qos.logback.classic.spi.ILoggingEvent
-import ch.qos.logback.core.AppenderBase
+import ch.qos.logback.core.read.ListAppender
 import io.micronaut.context.ApplicationContext
 import io.micronaut.http.annotation.Controller
 import io.micronaut.http.annotation.Get
@@ -12,10 +12,11 @@ import org.slf4j.LoggerFactory
 import spock.lang.Specification

 class HttpClientTraceLoggingSpec extends Specification {
+
     def 'full response'() {
         given:
         String loggerName = 'io.micronaut.http.client.HttpClientTraceLoggingSpec.' + UUID.randomUUID()
-        MemoryAppender appender = new MemoryAppender()
+        def appender = new ListAppender<ILoggingEvent>()
         Logger l = (Logger) LoggerFactory.getLogger(loggerName)
         l.addAppender(appender)
         l.setLevel(Level.ALL)
@@ -32,30 +33,15 @@ class HttpClientTraceLoggingSpec extends Specification {
         when:
         client.exchange("/get-full")
         then:
-        appender.events.any { it.contains('foo') }
+        appender.list.formattedMessage.any { it.contains('foo') }

         cleanup:
+        appender.stop()
         client.close()
         server.stop()
         ctx.stop()
     }

-
-    static class MemoryAppender extends AppenderBase<ILoggingEvent> {
-        private final List<String> events = new ArrayList<>()
-
-        @Override
-        protected void append(ILoggingEvent e) {
-            synchronized (events) {
-                events.add(e.toString())
-            }
-        }
-
-        List<String> getEvents() {
-            return events
-        }
-    }
-
     @Controller
     static class Ctrl {
         @Get("/get-full")
```

Also, I think we need to stop the appender in cleanup

**Review by timyates — CHANGES_REQUESTED** [review]
Think we need to close the appender...  Plus a suggestion to remove some code 👍

**Review by timyates — APPROVED** [review]

**Review by graemerocher — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]
