### PR TITLE
Merge field annotation metadata into setter argument annotation metadata

### LINKED ISSUE #4308: @MapFormat(keyFormat = RAW) not working when used with @ConfigurationProperties
### Steps to Reproduce

1. Simple configuration class (uses lombok)
```
@Data
@ConfigurationProperties("conf")
public class MyConfig {
    @MapFormat(keyFormat = RAW)
    private Map<String, String> animals;
}
```
2. Corresponding config in `application.yml`
```
conf:
  animals:
    VERY_FAST: rabbit
    VERY_SLOW: turtle
```

### Expected Behaviour
When accessing `MyConfig#getAnimals()`, the map should contain keys: `VERY_FAST` and `VERY_SLOW`

### Actual Behaviour
`MyConfig#getAnimals()` actually contains keys: `very-fast` and `very-slow`

### Environment Information

- **Operating System**: macOS 10.15.7
- **Micronaut Version**: 2.1.0 
- **JDK Version**: openjdk version "11.0.6" 2020-01-14 LTS

### Example Application

- https://github.com/john-pan9/micronaut-key-format-issue

### PR DESCRIPTION
**Pull request by mattmoss**
Fixes #4308

### CODE REVIEW

File: inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java [hunk 1]
```diff
@@ -270,4 +274,29 @@ private boolean isSuspend(VariableElement ve) {
...
+
+        final String expectedFieldName = NameUtils.getPropertyNameForSetter(methodName, writerPrefixes);
+
+        // Return the field corresponding to this writer.
+        return classElement.getEnclosedElements()
+                .stream()
+                .filter(element -> element.getKind() == ElementKind.FIELD)
+                .filter(field -> field.getSimpleName().contentEquals(expectedFieldName))
+                .findFirst()
+                .orElse(null);
```
Comment (graemerocher) [inline inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java:298]: This search doesn't make sense, should be use the `PropertyElement` API and `getBeanProperties`

Comment (mattmoss) [reply inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java:298]: @graemerocher , I don't follow. I don't see how to extract a field `javax.lang.model.element.Element` from the `PropertyElement`/`getBeanProperties` API. Maybe I'm looking in the wrong place...?
