### PR TITLE
Fix SSL context leak

### LINKED ISSUE #9409: Buffer leaks with HTTPS in 4.0.x branch
### Expected Behavior

No buffer leaks

### Actual Behaviour

```
18:02:59.493 [Test worker] ERROR io.netty.util.ResourceLeakDetector - LEAK: ReferenceCountedOpenSslContext.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
  Recent access records:
  Created at:
        Hint: expired
        io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:262)
        io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.<init>(ReferenceCountedOpenSslServerContext.java:74)
        io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.<init>(ReferenceCountedOpenSslServerContext.java:62)
        io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:480)
        io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:610)
        io.micronaut.http.server.netty.ssl.AbstractServerSslBuilder.build(AbstractServerSslBuilder.java:88)
        io.micronaut.http.server.netty.ssl.AbstractServerSslBuilder.build(AbstractServerSslBuilder.java:76)
        io.micronaut.http.server.netty.ssl.AbstractServerSslBuilder.build(AbstractServerSslBuilder.java:69)
        io.micronaut.http.server.netty.HttpPipelineBuilder.<init>(HttpPipelineBuilder.java:132)
```

### Steps To Reproduce

run `./gradlew http-server-netty:test`

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.0.x

### PR DESCRIPTION
**Pull request by yawkat**
This patch releases the SSL context when needed. Should fix #9409

### CODE REVIEW

File: http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java [hunk 1]
```diff
@@ -220,6 +221,7 @@ final void refresh() {
         for (Pool pool : pools.values()) {
             pool.forEachConnection(c -> ((Pool.ConnectionHolder) c).windDownConnection());
         }
+        ReferenceCountUtil.release(oldSslContext);
```
Comment (graemerocher) [inline http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java:224]: should this be in a `try/finally`?

File: http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java [hunk 2]
```diff
@@ -364,6 +366,8 @@ public final void shutdown() {
                 Thread.currentThread().interrupt();
             }
         }
+        ReferenceCountUtil.release(sslContext);
```
Comment (graemerocher) [inline http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java:369]: same here `finally` block?

**Review by graemerocher — CHANGES_REQUESTED** [review]

File: http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java (hunk 1 above)
Comment (yawkat) [reply http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java:224]: i think it's safer this way, we can't really recover from error in this method and if it does fail, it's better not to release the old context in case a connection may make use of the old context still

File: http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java (hunk 2 above)
Comment (yawkat) [reply http-client/src/main/java/io/micronaut/http/client/netty/ConnectionManager.java:369]: again can't really recover from failure and we don't want to release if there may be connections left to clean
