### PR TITLE
Split the runtime module into multiple modules

### LINKED ISSUE #3719: `RecoveryInterceptor` should be applied only on `@Recoverable` in the next major version
At the moment `@Fallback` can be used without  `@Recoverable` on the class.

https://github.com/micronaut-projects/micronaut-core/pull/3711

### LINKED ISSUE #8099: Decouple `HttpClient#create` from Jackson
The issue arose when using Micronaut Test Resources in combination with Micronaut serialization. The test resources project provides a client which has to be injected to the application code in order to be able to communicate with the test resources service. This client is compiled as part of the Micronaut Test Resources project and does _not_ use Micronaut serialization, but Jackson databind at runtime.

When this client is injected in an application which uses Micronaut Serialization, then the application fails to load:

```
io/micronaut/jackson/databind/JacksonDatabindMapper
java.lang.NoClassDefFoundError: io/micronaut/jackson/databind/JacksonDatabindMapper
	at io.micronaut.http.client.netty.DefaultHttpClient.createDefaultMediaTypeRegistry(DefaultHttpClient.java:1782)
	at io.micronaut.http.client.netty.DefaultHttpClient.<init>(DefaultHttpClient.java:399)
	at io.micronaut.http.client.netty.NettyHttpClientFactory.createNettyClient(NettyHttpClientFactory.java:132)
	at io.micronaut.http.client.netty.NettyHttpClientFactory.createNettyClient(NettyHttpClientFactory.java:121)
	at io.micronaut.http.client.netty.NettyHttpClientFactory.createClient(NettyHttpClientFactory.java:60)
	at io.micronaut.http.client.HttpClient.create(HttpClient.java:258)
	at io.micronaut.testresources.client.TestResourcesClientFactory.configuredAt(TestResourcesClientFactory.java:55)
	at io.micronaut.testresources.client.TestResourcesClientPropertySourceLoader$ClientTestResourcesResolver.lambda$findClient$1(TestResourcesClientPropertySourceLoader.java:65)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.micronaut.testresources.client.TestResourcesClientPropertySourceLoader$ClientTestResourcesResolver.findClient(TestResourcesClientPropertySourceLoader.java:65)
	at io.micronaut.testresources.client.TestResourcesClientPropertySourceLoader$ClientTestResourcesResolver.getPropertyEntries(TestResourcesClientPropertySourceLoader.java:48)
	at io.micronaut.testresources.core.LazyTestResourcesPropertySourceLoader$LazyPropertySource.computeKeys(LazyTestResourcesPropertySourceLoader.java:94)
	at io.micronaut.testresources.core.LazyTestResourcesPropertySourceLoader$LazyPropertySource.iterator(LazyTestResourcesPropertySourceLoader.java:86)
	at io.micronaut.context.env.PropertySourcePropertyResolver.processPropertySource(PropertySourcePropertyResolver.java:529)
	at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:434)
	at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:270)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:769)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:738)
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:242)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:193)
	at io.micronaut.test.extensions.AbstractMicronautExtension.startApplicationContext(AbstractMicronautExtension.java:433)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:314)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:84)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.ClassNotFoundException: io.micronaut.jackson.databind.JacksonDatabindMapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 81 more
```

See https://github.com/micronaut-projects/micronaut-test-resources/issues/103

This seems to be a blocker for using test resources.

### PR DESCRIPTION
**Pull request by graemerocher**
This PR splits the `micronaut-runtime` module into multiple modules.  The new modules are:

* `micronaut-retry` - The retry logic implementation is now optional. In order to support this by default declarative http clients are no longer automatically `@Recoverable` (Fixes #3719). This is a better arrangement as not everyone needs or uses fallbacks and recovery
* `micronaut-discovery` - The service discovery implementation is split into a separate module that is no longer required. The HTTP client module still depends on it though and would be nice to remove this coupling.

Following this change `micronaut-runtime` is just a meta module that depends on other modules. Other Micronaut modules should update and depend specifically on an individual module such not to pull in more than is necessary.

The motivation for this is to reduce the footprint of a new app since many features are not used (heartbeat, health checks, service discovery, retry etc.) unless you actually need them.

In addition the `micronaut-http-server-netty` module no longer depends on `micronaut-discovery`, `micronaut-health` and `micronaut-websocket`. If users want any of those features then they can add them individually to their application. Micronaut Launch will need to be updated with new feature for WebSocket support. It is probably not necessary to include new features for discovery and health as these will be transitively pulled by the Management module.

Also fixes #8099 by introducing a new interface to resolve the `JsonMapper`

Note this PR also moves some functionality into other modules:

https://github.com/micronaut-projects/micronaut-kotlin/pull/440
https://github.com/micronaut-projects/micronaut-reactor/pull/237

This change also switches Micronaut's integration to GraalVM to be largely runtime initialized including logging. Only Micronaut metadata is build time initialized. This change improves startup time and reduces the size of the images we build.

### CODE REVIEW

File: core/src/main/java/io/micronaut/core/graal/AutomaticFeatureUtils.java [hunk 1]
```diff
@@ -31,7 +31,7 @@
 import java.util.Optional;
 
 /**
- * Utility methods for implementing Graal's {@link com.oracle.svm.core.annotate.AutomaticFeature}.
+ * Utility methods for implementing GraalVM
```
Comment (sdelamo) [inline core/src/main/java/io/micronaut/core/graal/AutomaticFeatureUtils.java]:
```suggestion
 * Utility methods for implementing GraalVM.
```

File: test-suite-kotlin/src/test/kotlin/io/micronaut/MdcPropagationSpec.kt [hunk 2]
```diff
@@ -1,176 +0,0 @@
...
-import org.reactivestreams.Publisher
-import org.slf4j.LoggerFactory
-import org.slf4j.MDC
-import reactor.core.publisher.Flux
-import reactor.core.publisher.Mono
-import reactor.core.publisher.toFlux
-import java.net.URI
-import java.util.*
-
-class MdcPropagationSpec {
```
Comment (sdelamo) [inline test-suite-kotlin/src/test/kotlin/io/micronaut/MdcPropagationSpec.kt:38]: why did you remove this test?

File: core/src/main/java/io/micronaut/core/io/scan/DefaultClassPathResourceLoader.java [hunk 3]
```diff
@@ -40,8 +40,6 @@
  */
 public class DefaultClassPathResourceLoader implements ClassPathResourceLoader {
 
-    private static final Logger LOG = LoggerFactory.getLogger(DefaultClassPathResourceLoader.class);
```
Comment (sdelamo) [inline core/src/main/java/io/micronaut/core/io/scan/DefaultClassPathResourceLoader.java:43]: what is the motivation of this change?

File: inject/src/main/java/io/micronaut/context/AbstractBeanContextConditional.java [hunk 4]
```diff
@@ -38,8 +38,6 @@
 @Internal
 abstract class AbstractBeanContextConditional implements BeanContextConditional, AnnotationMetadataProvider {
 
-    static final Logger LOG = LoggerFactory.getLogger(Condition.class);
```
Comment (sdelamo) [inline inject/src/main/java/io/micronaut/context/AbstractBeanContextConditional.java:41]: why do we need to do this change?

File: http-client/src/test/groovy/io/micronaut/http/client/aop/ReactorJavaFallbackSpec.groovy [hunk 5]
```diff
@@ -97,6 +98,7 @@ class ReactorJavaFallbackSpec extends Specification{
 
     @Requires(property = 'spec.name', value = 'ReactorJavaFallbackSpec')
     @Client('/rxjava/fallback/books')
+    @Recoverable
```
Comment (sdelamo) [inline http-client/src/test/groovy/io/micronaut/http/client/aop/ReactorJavaFallbackSpec.groovy:101]: We need to document that users will need to add `@Recoverable` to their `@Client` if they want that functionality.

**Review by sdelamo — CHANGES_REQUESTED** [review]
Not sure what's the motivation/why do we need these static classes such as `EventLogger` and `ConditionLog`.

File: core/src/main/java/io/micronaut/core/io/scan/DefaultClassPathResourceLoader.java (hunk 3 above)
Comment (dstepanov) [reply core/src/main/java/io/micronaut/core/io/scan/DefaultClassPathResourceLoader.java:43]: Probably to avoid native build time processing

**Review by dstepanov — APPROVED** [review]

**Comment by dstepanov** [comment]
I have an issue from a long time ago about removing `@Recoverable` from `@Client` https://github.com/micronaut-projects/micronaut-core/issues/3719

File: test-suite-kotlin/src/test/kotlin/io/micronaut/MdcPropagationSpec.kt (hunk 2 above)
Comment (graemerocher) [reply test-suite-kotlin/src/test/kotlin/io/micronaut/MdcPropagationSpec.kt:38]: needs moving to the Reactor module where the instrumentation now lives

File: core/src/main/java/io/micronaut/core/io/scan/DefaultClassPathResourceLoader.java (hunk 3 above)
Comment (graemerocher) [reply core/src/main/java/io/micronaut/core/io/scan/DefaultClassPathResourceLoader.java:43]: To avoid the logs being initialized at build time

File: inject/src/main/java/io/micronaut/context/AbstractBeanContextConditional.java (hunk 4 above)
Comment (graemerocher) [reply inject/src/main/java/io/micronaut/context/AbstractBeanContextConditional.java:41]: To avoid the logs being initialized at build time

File: http-client/src/test/groovy/io/micronaut/http/client/aop/ReactorJavaFallbackSpec.groovy (hunk 5 above)
Comment (graemerocher) [reply http-client/src/test/groovy/io/micronaut/http/client/aop/ReactorJavaFallbackSpec.groovy:101]: Agreed

Comment (graemerocher) [reply http-client/src/test/groovy/io/micronaut/http/client/aop/ReactorJavaFallbackSpec.groovy:101]: Added docs

**Comment by graemerocher** [comment]
> Not sure what's the motivation/why do we need these static classes such as `EventLogger` and `ConditionLog`.

They are to avoid initializing logging at build time

**Comment by graemerocher** [comment]
The tests in `function` are failing for some unknown reason related to Gradle Enterprise. @melix is investigating.

**Comment by graemerocher** [comment]
I rolled back to the change to split `HeartBeatConfiguration` out of the `io.micronaut.health` package to avoid breaking binary compatibility with the existing discovery modules

**Review by sdelamo — APPROVED** [review]
