### PR TITLE
Correct cookies in simple request/response

### LINKED ISSUE #10235: MutableHttpRequest doesn't set multiple cookies properly
### Expected Behavior

MutableHttpRequest (specifically NettyMutableHttpRequest)'s `cookies(Set<Cookie>)` method should result in all cookies being set in the request

### Actual Behaviour

`cookies(Set<Cookie>)` results in only one cookie being set (the last one in the set).  

This appears to be an issue with the NettyMutableHttpRequest `cookie` method, which overrides any existing cookie header with the new cookie input.

### Steps To Reproduce

invoke the following code in an http-enabled project and observe the resulting request
```
@ServerFilter("/**")
class IncomingRequestFilter {

    @RequestFilter
    @ExecuteOn(TaskExecutors.BLOCKING)
    void filterRequest(MutableHttpRequest<?> request) {
        Cookie newCookie2 = Cookie.of("COOKIE_1", "one")
        Cookie newCookie = Cookie.of("COOKIE_2", "two")

        Set<Cookie> cookies = new HashSet<>()
        cookies.addAll(newCookie)
        cookies.addAll(newCookie2)

        request.cookies(cookies)
    }
}
```

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.1.6

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes https://github.com/micronaut-projects/micronaut-core/issues/10235

### CODE REVIEW

File: http/src/main/java/io/micronaut/http/simple/SimpleHttpRequest.java [hunk 1]
```diff
@@ -69,17 +71,25 @@ public SimpleHttpRequest(HttpMethod method, String url, B body) {
...
     public MutableHttpRequest<B> cookies(Set<Cookie> cookies) {
         for (Cookie cookie: cookies) {
-            cookie(cookie);
+            this.cookies.put(cookie.getName(), cookie);
         }
+        updateCookies();
         return this;
     }
-
     @Override
```
Comment (yawkat) [inline http/src/main/java/io/micronaut/http/simple/SimpleHttpRequest.java]:
```suggestion

    @Override
```

**Review by yawkat — APPROVED** [review]
