### PR TITLE
Cache JsonMapper in DefaultNettyHttpClientRegistry

### LINKED ISSUE #7087: Declarative HttpClient blocking on http registry getClientKey
### Expected Behavior

Expect no blocking on `beanContext.getBean(JsonMapper.class)` in `io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry#getClientKey` while using declarative http client.

### Actual Behaviour

Lot of blocking on `beanContext.getBean(JsonMapper.class)` in `io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry#getClientKey` while using declarative http client for lots of concurrent calls to various clients.

### Steps To Reproduce

Hard to reproduce without lots of concurrent calls to many declarative http clients.

### Environment Information

Alpine Linux v3.14
openjdk 11.0.11 2021-04-20

### Example Application

_No response_

### Version

3.3.4

### PR DESCRIPTION
**Pull request by yawkat**
This avoids a getBean call every time.
Fixes #7087

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

File: http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java [hunk 1]
```diff
@@ -125,6 +126,7 @@
      * @param eventLoopGroupFactory           The event loop group factory
      * @param beanContext                     The bean context
      * @param invocationInstrumenterFactories The invocation instrumenter factories
+     * @param jsonMapper
```
Comment (sdelamo) [inline http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java]: It misses the description of the Javadoc parameter

**Review by sdelamo — CHANGES_REQUESTED** [review]

File: http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java (hunk 1 above)
Comment (sdelamo) [reply http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java]: resolved via https://github.com/micronaut-projects/micronaut-core/pull/7117/commits/d0ab0629290e48d1d0cf1a5d06e571004085d41c

**Review by sdelamo — APPROVED** [review]
