### PR TITLE
Move to URI for HTTP client API to support ws/wss schemes

### LINKED ISSUE #5711: using RxWebSocketClient with wss protocol
It is not possible to create an RxWebSocketClient with wss protocol.
It fails in
`io.micronaut.http.client.DefaultLoadBalancerResolver.resolve(String...)`
on the constructor-call to new URL(reference)

```
            try {
                URL url = new URL(reference);
                return Optional.of(LoadBalancer.fixed(url));
            } catch (MalformedURLException e) {
                return Optional.empty();
            }
```

`java.net.MalformedURLException: unknown protocol: wss`

Or is it me doing something fundamentally wrong?

### Steps to Reproduce

1. create an RxWebSocketClient using an url with wss-protocol
i tested with following url which works fine with in a browser-test (js websocket)
> wss://stream.binance.com:9443/stream?streams=btcusdt@kline_5m/adausdt@kline_5m

### Expected Behaviour
Websocket should provide data

### Actual Behaviour
```
Caused by: io.micronaut.http.client.exceptions.HttpClientException: Invalid service reference [wss://stream.binance.com:9443] specified to @Client
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.lambda$null$0(RxNettyHttpClientRegistry.java:235)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.lambda$getClient$1(RxNettyHttpClientRegistry.java:234)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.getClient(RxNettyHttpClientRegistry.java:197)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.getClient(RxNettyHttpClientRegistry.java:148)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.resolveClient(RxNettyHttpClientRegistry.java:392)
	at io.micronaut.http.client.netty.RxNettyHttpClientRegistry.httpClient(RxNettyHttpClientRegistry.java:193)
	at io.micronaut.http.client.netty.$RxNettyHttpClientRegistry$HttpClient0Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:118)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1930)
	... 27 common frames omitted
```

### Environment Information

- **Operating System**: win10
- **Micronaut Version:** 2.41
- **JDK Version:** 11

### PR DESCRIPTION
**Pull request by yawkat**
- `java.net.URL` does not support the ws/wss schemes out-of-the-box. We could implement a mock `URLStreamHandler` for them, but this seems hacky, since we never actually use the `URLConnection` support `URL` provides. So instead, this patch migrates all client APIs to `URI`s, deprecating the old `URL`-based methods.
- Some checks in `DefaultHttpClient` already supported ws/wss, but others did not. To unify this, this patch extracts the relevant check to an `isSecureScheme` method.
- Otherwise, ws/wss are completely identical to http/https (https://fetch.spec.whatwg.org/#websocket-opening-handshake : "There is no real reason for WebSocket to have distinct schemes, it’s a legacy artefact."), so no further modification of the client should be necessary.

Resolves #5711

### CODE REVIEW

**Comment by yawkat** [comment]
Not sure what to do about the `create(null)` case. The test failures come from that, because it can't decide between the URI and the URL factory methods. This is only a source compatibility issue, not a binary compatibility one, and it's easy to fix in client code. Does it still mean we have to fix this? One alternative would be giving the new methods a different name.

File: http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClient.java [hunk 1]
```diff
@@ -156,8 +159,37 @@ static StreamingHttpClient create(@Nullable URL url) {
...
+
+    /**
+     * Create a new {@link StreamingHttpClient}.
+     * Note that this method should only be used outside of the context of a Micronaut application.
+     * The returned {@link StreamingHttpClient} is not subject to dependency injection.
+     * The creator is responsible for closing the client to avoid leaking connections.
+     * Within a Micronaut application use {@link jakarta.inject.Inject} to inject a client instead.
+     *
+     * @param uri The base URI
+     * @return The client
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClient.java]: add `@since` and `@NonNull` to return type

File: http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClient.java [hunk 2]
```diff
@@ -156,8 +159,37 @@ static StreamingHttpClient create(@Nullable URL url) {
...
+    }
+
+    /**
+     * Create a new {@link StreamingHttpClient} with the specified configuration. Note that this method should only be used
+     * outside of the context of an application. Within Micronaut use {@link jakarta.inject.Inject} to inject a client instead
+     *
+     * @param uri The base URI
+     * @param configuration the client configuration
+     * @return The client
+     * @since 2.2.0
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClient.java]: `@since` seems incorrect here

File: http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClient.java [hunk 3]
```diff
@@ -156,8 +159,37 @@ static StreamingHttpClient create(@Nullable URL url) {
...
+     */
+    static StreamingHttpClient create(@Nullable URI uri, @NonNull HttpClientConfiguration configuration) {
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClient.java]: Add `@NonNull` to return type

File: http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java [hunk 4]
```diff
@@ -47,8 +58,50 @@
...
+    }
+
+    /**
+     * Create a new {@link StreamingHttpClient} with the specified configuration. Note that this method should only be used
+     * outside of the context of an application. Within Micronaut use {@link jakarta.inject.Inject} to inject a client instead
+     *
+     * @param uri The base URI
+     * @param configuration The client configuration
+     * @return The client
+     * @since 2.2.0
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java]: incorrect `@since`

File: http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java [hunk 5]
```diff
@@ -47,8 +58,50 @@
...
+            throw new IllegalArgumentException(e);
+        }
+    }
+
+    /**
+     * Create a new {@link StreamingHttpClient}. Note that this method should only be used outside of the context of an application. Within Micronaut use
+     * {@link jakarta.inject.Inject} to inject a client instead
+     *
+     * @param uri The base URI
+     * @return The client
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java]: add `@since`

File: http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java [hunk 6]
```diff
@@ -47,8 +58,50 @@
...
+     */
+    @NonNull
+    default StreamingHttpClient createStreamingClient(@Nullable URI uri) {
+        try {
+            return createStreamingClient(uri != null ? uri.toURL() : null);
+        } catch (MalformedURLException e) {
+            throw new UnsupportedOperationException(e);
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java]: better to throw `HttpClientException` or `IllegalArgumentException`

File: http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java [hunk 7]
```diff
@@ -47,8 +58,50 @@
...
+     * @param configuration The client configuration
+     * @return The client
+     * @since 2.2.0
+     */
+    @NonNull
+    default StreamingHttpClient createStreamingClient(@Nullable URI uri, @NonNull HttpClientConfiguration configuration) {
+        try {
+            return createStreamingClient(uri != null ? uri.toURL() : null, configuration);
+        } catch (MalformedURLException e) {
+            throw new UnsupportedOperationException(e);
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java]: better to throw `HttpClientException` or `IllegalArgumentException`

File: http-client-core/src/main/java/io/micronaut/http/client/sse/SseClient.java [hunk 8]
```diff
@@ -138,8 +141,37 @@ static SseClient create(@Nullable URL url) {
...
+
+    /**
+     * Create a new {@link SseClient}.
+     * Note that this method should only be used outside of the context of a Micronaut application.
+     * The returned {@link SseClient} is not subject to dependency injection.
+     * The creator is responsible for closing the client to avoid leaking connections.
+     * Within a Micronaut application use {@link jakarta.inject.Inject} to inject a client instead.
+     *
+     * @param uri The base URI
+     * @return The client
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/sse/SseClient.java]: Add `@since` and `@NonNull` to return type

File: http-client-core/src/main/java/io/micronaut/http/client/sse/SseClient.java [hunk 9]
```diff
@@ -138,8 +141,37 @@ static SseClient create(@Nullable URL url) {
...
+    }
+
+    /**
+     * Create a new {@link SseClient} with the specified configuration. Note that this method should only be used
+     * outside of the context of an application. Within Micronaut use {@link jakarta.inject.Inject} to inject a client instead
+     *
+     * @param uri The base URI
+     * @param configuration the client configuration
+     * @return The client
+     * @since 2.2.0
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/sse/SseClient.java]: incorrect `@since`

File: http-client-core/src/main/java/io/micronaut/http/client/sse/SseClientFactory.java [hunk 10]
```diff
@@ -48,8 +59,50 @@
...
+     *
+     * @param uri The base URI
+     * @return The client
+     */
+    @NonNull
+    default SseClient createSseClient(@Nullable URI uri) {
+        try {
+            return createSseClient(uri != null ? uri.toURL() : null);
+        } catch (MalformedURLException e) {
+            throw new UnsupportedOperationException(e);
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/sse/SseClientFactory.java]: better to throw `HttpClientException` or `IllegalArgumentException`

File: http-client-core/src/main/java/io/micronaut/http/client/sse/SseClientFactory.java [hunk 11]
```diff
@@ -48,8 +59,50 @@
...
+     * @param configuration the client configuration
+     * @return The client
+     * @since 2.2.0
+     */
+    @NonNull
+    default SseClient createSseClient(@Nullable URI uri, @NonNull HttpClientConfiguration configuration) {
+        try {
+            return createSseClient(uri != null ? uri.toURL() : null, configuration);
+        } catch (MalformedURLException e) {
+            throw new UnsupportedOperationException(e);
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/sse/SseClientFactory.java]: better to throw `HttpClientException` or `IllegalArgumentException`

File: http-client-core/src/main/java/io/micronaut/http/client/sse/SseClientFactory.java [hunk 12]
```diff
@@ -48,8 +59,50 @@
...
+    }
+
+    /**
+     * Create a new {@link SseClient} with the specified configuration. Note that this method should only be used
+     * outside of the context of an application. Within Micronaut use {@link jakarta.inject.Inject} to inject a client instead
+     *
+     * @param uri The base URI
+     * @param configuration the client configuration
+     * @return The client
+     * @since 2.2.0
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/sse/SseClientFactory.java]: incorrect `@since`

File: http-client-core/src/main/java/io/micronaut/http/client/sse/SseClientFactory.java [hunk 13]
```diff
@@ -48,8 +59,50 @@
...
+            throw new IllegalArgumentException(e);
+        }
+    }
+
+    /**
+     * Create a new {@link SseClient}. Note that this method should only be used outside of the context of an application. Within Micronaut use
+     * {@link jakarta.inject.Inject} to inject a client instead
+     *
+     * @param uri The base URI
+     * @return The client
```
Comment (graemerocher) [inline http-client-core/src/main/java/io/micronaut/http/client/sse/SseClientFactory.java]: add `@since`

File: websocket/src/main/java/io/micronaut/websocket/WebSocketClient.java [hunk 14]
```diff
@@ -125,9 +127,38 @@ static WebSocketClient create(@Nullable URL url) {
...
+    }
+
+    /**
+     * Create a new {@link WebSocketClient} with the specified configuration. Note that this method should only be used
+     * outside of the context of an application. Within Micronaut use {@link jakarta.inject.Inject} to inject a client instead
+     *
+     * @param uri The base URI
+     * @param configuration the client configuration
+     * @return The client
+     * @since 2.2.0
```
Comment (graemerocher) [inline websocket/src/main/java/io/micronaut/websocket/WebSocketClient.java]: Incorrect `@since` and add `@NonNull` to return type

File: websocket/src/main/java/io/micronaut/websocket/WebSocketClient.java [hunk 15]
```diff
@@ -125,9 +127,38 @@ static WebSocketClient create(@Nullable URL url) {
...
 
+    /**
+     * Create a new {@link WebSocketClient}.
+     * Note that this method should only be used outside of the context of a Micronaut application.
+     * The returned {@link WebSocketClient} is not subject to dependency injection.
+     * The creator is responsible for closing the client to avoid leaking connections.
+     * Within a Micronaut application use {@link jakarta.inject.Inject} to inject a client instead.
+     *
+     * @param uri The base URI
+     * @return The client
```
Comment (graemerocher) [inline websocket/src/main/java/io/micronaut/websocket/WebSocketClient.java:148]: add `@since`

File: websocket/src/main/java/io/micronaut/websocket/WebSocketClientFactory.java [hunk 16]
```diff
@@ -47,8 +58,49 @@
...
+     *
+     * @param uri The base URI
+     * @return The client
+     */
+    @NonNull
+    default WebSocketClient createWebSocketClient(@Nullable URI uri) {
+        try {
+            return createWebSocketClient(uri != null ? uri.toURL() : null);
+        } catch (MalformedURLException e) {
+            throw new UnsupportedOperationException(e);
```
Comment (graemerocher) [inline websocket/src/main/java/io/micronaut/websocket/WebSocketClientFactory.java:86]: better to throw `HttpClientException` or `IllegalArgumentException`

File: websocket/src/main/java/io/micronaut/websocket/WebSocketClientFactory.java [hunk 17]
```diff
@@ -47,8 +58,49 @@
...
+            throw new IllegalArgumentException(e);
+        }
+    }
+
+    /**
+     * Create a new {@link WebSocketClient}. Note that this method should only be used outside of the context of an application. Within Micronaut use
+     * {@link jakarta.inject.Inject} to inject a client instead
+     *
+     * @param uri The base URI
+     * @return The client
```
Comment (graemerocher) [inline websocket/src/main/java/io/micronaut/websocket/WebSocketClientFactory.java:78]: add `@since`

File: websocket/src/main/java/io/micronaut/websocket/WebSocketClientFactory.java [hunk 18]
```diff
@@ -47,8 +58,49 @@
...
+        }
+    }
+
+    /**
+     * Create a new {@link WebSocketClient} with the specified configuration. Note that this method should only be used outside of the context of an application. Within Micronaut use
+     * {@link jakarta.inject.Inject} to inject a client instead
+     *
+     * @param uri The base URI
+     * @param configuration The client configuration
+     * @return The client
```
Comment (graemerocher) [inline websocket/src/main/java/io/micronaut/websocket/WebSocketClientFactory.java:96]: add `@since`

File: websocket/src/main/java/io/micronaut/websocket/WebSocketClientFactory.java [hunk 19]
```diff
@@ -36,9 +39,17 @@
      *
      * @param url The base URL
      * @return The client
+     * @deprecated Use {@link #createWebSocketClient(URI)} instead
```
Comment (graemerocher) [inline websocket/src/main/java/io/micronaut/websocket/WebSocketClientFactory.java:42]: add `@since`

**Review by graemerocher — CHANGES_REQUESTED** [review]

File: http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java (hunk 6 above)
Comment (yawkat) [reply http-client-core/src/main/java/io/micronaut/http/client/StreamingHttpClientFactory.java]: I think `UnsupportedOperationException` is better here because this will only happen if `createStreamingClient(URI)` hasn't been implemented yet, and the scheme is ws/wss

**Comment by jameskleeh** [comment]
Why do we need the `create(@Nullable URI uri) {` methods in anything other than the WebSocketClient?

**Comment by yawkat** [comment]
We don't strictly need them, but it seems sensible to move the API to URI eventually, for consistency.

**Comment by sdelamo** [comment]
We have `create(URL)` and `create(URL, HttpClientConfiguration)` static methods in [rxjava2](https://github.com/micronaut-projects/micronaut-rxjava2), [rxjava3](https://github.com/micronaut-projects/micronaut-rxjava3) and [reactor](https://github.com/micronaut-projects/micronaut-reactor) modules. We should do this change in the reactive libraries as well.

**Review by jameskleeh — CHANGES_REQUESTED** [review]
Given the possibility for breakage with passing a null I think we should remove the URI conversion for the static methods not in WebsocketClient

**Comment by yawkat** [comment]
Is the breakage acceptable for `WebSocketClient`?

**Comment by jameskleeh** [comment]
I think the cost/benefit works out in my opinion for `WebSocketClient`

**Review by graemerocher — APPROVED** [review]

**Review by jameskleeh — CHANGES_REQUESTED** [review]
I would like to see some tests using ws:// and wss://. Also please add to breaks.adoc the source compatibility with `create(null)`

**Comment by graemerocher** [comment]
There are already tests:

https://github.com/micronaut-projects/micronaut-core/pull/6494/files#diff-50c9ef7968abe9afc19ca01d98e5041ec63797f25042f6540bbe6ae8e73e1f9dR109

and 

https://github.com/micronaut-projects/micronaut-core/pull/6494/files#diff-50c9ef7968abe9afc19ca01d98e5041ec63797f25042f6540bbe6ae8e73e1f9dR194

Docs make sense though

**Comment by jameskleeh** [comment]
Ah OK missed that
