### PR TITLE
Replaces improvement

### LINKED ISSUE #550: Can't replace default MongoClient with @Replaces
I'm trying to create an alternative `MongoClient` factory for a Kotlin project (to use [kmongo](https://litote.org/kmongo/)).  I tried this first using `@Named` as a qualifier (see #549 -- works in Java, fails in Kotlin).

I then tried using the `@Replaces` annotation in my `MongoClient` factory:

```kotlin
@Requirements(
        Requires(classes = arrayOf(MongoClient::class)),
        Requires(beans = arrayOf(DefaultMongoConfiguration::class)))
@Factory
class MyMongoClientFactory {

    companion object: KLogging()

    @Bean(preDestroy = "close")
    @Singleton
    @Replaces(MongoClient::class)
    fun myMongoClient(configuration: DefaultMongoConfiguration): MongoClient {
        logger.info { "===== creating myMongoClient" }
        return MongoClient(configuration.buildURI())
    }
}
```

Injection into controller:
```kotlin
    @Inject
    private lateinit var mongoClient: MongoClient
```

The Java code is very similar...except...well, Java.  The Java and Kotlin code both fail with the same `NoSuchBeanException`.  Here's a stacktrace (nearly identical in both Java and Kotlin) with debug logging before the error:

```
21:51:04.085 [pool-1-thread-5] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: class com.mongodb.MongoClient
21:51:04.086 [pool-1-thread-5] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: class io.micronaut.configuration.mongo.reactive.DefaultMongoConfiguration
21:51:04.087 [pool-1-thread-5] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.configuration.mongo.reactive.DefaultMongoConfiguration] for type: class io.micronaut.configuration.mongo.reactive.DefaultMongoConfiguration
21:51:04.087 [pool-1-thread-5] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.configuration.mongo.reactive.DefaultMongoConfiguration]
21:51:04.087 [pool-1-thread-5] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [Definition: io.micronaut.configuration.mongo.reactive.DefaultMongoConfiguration] for type: io.micronaut.configuration.mongo.reactive.DefaultMongoConfiguration 
21:51:04.087 [pool-1-thread-5] DEBUG i.m.context.DefaultBeanContext - Bean [class com.mongodb.MongoClient] replaces existing bean of type [class com.mongodb.MongoClient]
21:51:04.088 [pool-1-thread-5] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [] for type: class com.mongodb.MongoClient
21:51:04.091 [nioEventLoopGroup-1-2] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: interface io.micronaut.http.server.exceptions.ExceptionHandler
21:51:04.093 [nioEventLoopGroup-1-2] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.http.server.exceptions.ContentLengthExceededHandler, Definition: io.micronaut.http.server.exceptions.JsonExceptionHandler, Definition: io.micronaut.http.server.exceptions.UnsatisfiedArgumentHandler, Definition: io.micronaut.http.server.exceptions.HttpStatusHandler, Definition: io.micronaut.http.server.exceptions.ConversionErrorHandler, Definition: io.micronaut.http.server.netty.converters.UnsatisfiedRouteHandler, Definition: io.micronaut.http.server.netty.converters.DuplicateRouteHandler, Definition: io.micronaut.validation.exceptions.ConstraintExceptionHandler] for type: interface io.micronaut.http.server.exceptions.ExceptionHandler
21:51:04.093 [nioEventLoopGroup-1-2] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.http.server.exceptions.ContentLengthExceededHandler, Definition: io.micronaut.http.server.exceptions.JsonExceptionHandler, Definition: io.micronaut.http.server.exceptions.UnsatisfiedArgumentHandler, Definition: io.micronaut.http.server.exceptions.HttpStatusHandler, Definition: io.micronaut.http.server.exceptions.ConversionErrorHandler, Definition: io.micronaut.http.server.netty.converters.UnsatisfiedRouteHandler, Definition: io.micronaut.http.server.netty.converters.DuplicateRouteHandler, Definition: io.micronaut.validation.exceptions.ConstraintExceptionHandler]
21:51:04.093 [nioEventLoopGroup-1-2] DEBUG i.m.context.DefaultBeanContext - Qualifying bean [io.micronaut.http.server.exceptions.ExceptionHandler] for qualifier: <DependencyInjectionException,Object> 
21:51:04.094 [nioEventLoopGroup-1-2] DEBUG i.m.context.DefaultBeanContext - No qualifying beans of type [io.micronaut.http.server.exceptions.ExceptionHandler] found for qualifier: <DependencyInjectionException,Object> 

21:32:09.065 [nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for field [mongoClient] of class: example.HelloController

Path Taken: HelloController.mongoClient
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [mongoClient] of class: example.HelloController

Path Taken: HelloController.mongoClient
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1294)
	at io.micronaut.context.AbstractBeanDefinition.injectBeanField(AbstractBeanDefinition.java:691)
	at example.$HelloControllerDefinition.injectBean(Unknown Source)
	at example.$HelloControllerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1252)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1677)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1447)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1427)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:493)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2119)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:290)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:123)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$12(RoutingInBoundHandler.java:1175)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
	at io.reactivex.Flowable.subscribe(Flowable.java:14409)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.Flowable.subscribe(Flowable.java:14409)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:14409)
	at io.reactivex.Flowable.subscribe(Flowable.java:14359)
	at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:53)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
	at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:53)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14409)
	at io.reactivex.Flowable.subscribe(Flowable.java:14356)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:261)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:226)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [com.mongodb.MongoClient] exists. If you are using Java or Kotlin make sure you have enabled annotation processing.
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1433)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:852)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1286)
	... 31 common frames omitted
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

I modified the `hello-world-java` and `hello-world-kotlin` examples to reproduce the problem.

1. Clone [my fork of micronaut-examples](https://github.com/mmindenhall/micronaut-examples)
2. `git checkout replace-mongodb-client`
3. `cd hello-world-java`
1. `./gradlew run`
1.  GET http://localhost:8080/hello/dude in browser or http client
    1.  `NoSuchBeanException` is thrown
1. `cd ../hello-world-kotlin`
1. `./gradlew run`
1.  GET http://localhost:8080/hello/dude in browser or http client
    1.  `NoSuchBeanException` is thrown

### Expected Behaviour

The `MongoClient` produced from `DefaultMongoClientFactory` is replaced (in both Java and Kotlin).

### Actual Behaviour

`NoSuchBeanException` in both Java and Kotlin.

### Environment Information

- **Operating System**: Mac OS 10.13.6
- **Micronaut Version:** 1.0.0.M4 _and_ 1.0.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8.0_152

### Example Application

See steps to reproduce above.

### PR DESCRIPTION
**Pull request by jameskleeh**
Fixes #550

### CODE REVIEW

File: inject-java/src/test/java/io/micronaut/docs/replaces/MockBookService.java [hunk 1]
```diff
@@ -31,7 +31,6 @@
  */
 // tag::class[]
 @Replaces(JdbcBookService.class) // <1>
-@Requires(env = Environment.TEST) // <2>
```
Comment (graemerocher) [inline inject-java/src/test/java/io/micronaut/docs/replaces/MockBookService.java]: Should this have been deleted?

File: inject/src/main/java/io/micronaut/inject/BeanDefinition.java [hunk 2]
```diff
@@ -69,6 +69,11 @@
     @Override
     Class<T> getBeanType();
 
+    /**
+     * @return The type that declares this definition, null if not applicable.
+     */
+    Class<?> getDeclaringType();
```
Comment (graemerocher) [inline inject/src/main/java/io/micronaut/inject/BeanDefinition.java]: Maybe return `Optional`?

File: inject-java/src/test/java/io/micronaut/docs/replaces/MockBookService.java (hunk 1 above)
Comment (jameskleeh) [reply inject-java/src/test/java/io/micronaut/docs/replaces/MockBookService.java]: Yeah - the class in the docs is defined in `src/test`. Since the test environment is enabled by default there, I thought it would cause users to believe that the requires is necessary

File: inject/src/main/java/io/micronaut/inject/BeanDefinition.java (hunk 2 above)
Comment (jameskleeh) [reply inject/src/main/java/io/micronaut/inject/BeanDefinition.java]: Done
