### PR TITLE
Groovy properties should expose read/write methods. Fixes #5129

### LINKED ISSUE #5129: 2.4 `withValue` is incorrectly generated for Groovy
```
 public Object withValueInternal(Object var1, Object var2) {
        return this.getDeclaringBean().instantiate(new Object[0]);
    }
```

### PR DESCRIPTION
**Pull request by graemerocher**
Currently `GroovyPropertyElement` doesn't expose read/write methods for the property which means they have to be handled differently.

This alters `GroovyPropertyElement` with new synthetic read/write methods so the behaviour is consistent with when getters/setters are defined.

Fixes #5129

### CODE REVIEW

File: inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java [hunk 1]
```diff
@@ -523,6 +529,43 @@ public ClassElement getType() {
...
+                                GroovyClassElement.this,
+                                annotationMetadata,
+                                getType(),
+                                getGenericType(),
+                                getGetterName(propertyName, getType())
+                        ));
+                    }
+
+                    private String getGetterName(String propertyName, ClassElement type) {
+                        final String prefix;
```
Comment (jameskleeh) [inline inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java]: There are methods in NameUtils to do this

Comment (graemerocher) [reply inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java]: Changed to use them, hopefully they are consistent with how Groovy behaves
