### PR TITLE
Preserving Body Related Headers When Following 307 or 308 Redirects

### LINKED ISSUE #12265: Micronaut Http Client Dropping content-type Header on 307 Response
### Expected Behavior

The content-type header should be preserved from the initial request, in the subsequent redirected request. 

### Actual Behaviour

The content-type header is dropped from the subsequent request. See https://github.com/micronaut-projects/micronaut-core/blob/4.10.x/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L239. 

### Steps To Reproduce

I recreated this by creating a mock server that returned a 307 response from an endpoint, and redirected the client to some other endpoint on the server.

```
@Client("https://everett-testing.free.beeceptor.com")
public interface TodoClient {

    @Produces(MediaType.APPLICATION_FORM_URLENCODED)
    @Post("/todos")
    Mono<HttpResponse<List<Todo>>> fetchTodos(@Body TodoRequest todoRequest);
}

@Serdeable  
public class Todo {  
    private Integer id;  
    private String task;  
    private Boolean completed;
    // ... getter & setter
}

@Serdeable  
public class TodoRequest {  
    private String q;  
  // ... getter & setter
}

@MicronautTest
class TodoClientTest {

    @Inject
    TodoClient todoClient;

    @Test
    void testing() {
        TodoRequest todoRequest = new TodoRequest();
        todoRequest.setQ("something is here");

        Mono<HttpResponse<List<Todo>>> clientResponse = todoClient.fetchTodos(todoRequest);

        StepVerifier.create(clientResponse)
            .consumeNextWith(response -> {
                assertThat(response).isNotNull();
            })
            .verifyComplete();
    }
}
```

https://github.com/micronaut-projects/micronaut-core/blob/4.10.x/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L2071
Image

Image

Image

### Environment Information

openjdk 17.0.16 2025-07-15 LTS

### Example Application

_No response_

### Version

4.10.x

### PR DESCRIPTION
**Pull request by everett-hayes**
### Summary

Fixes https://github.com/micronaut-projects/micronaut-core/issues/12265. 

This PR resolves an issue where when following a 307 or 308 redirect, request headers that related to the request body were dropped.

This stems from changes made in https://github.com/micronaut-projects/micronaut-core/issues/6417 dealing with other 3xx responses. When converting from POST -> GET we stripped `content-type` and `content-length` since we were also stripping the request body.

However in a situation where the http method & body are preserved, we can't strip these headers.

As discussed in https://github.com/micronaut-projects/micronaut-core/issues/12265, we tested curl & various browsers, and found this was the behavior.

---

### Local testing

Before:
mock-server-request-bodies

After, I setup a mock server, and using the changes in this branch observed:
end-to-end-working-now

---

First time opening a micronaut PR, let me know if I missed anything!

### CODE REVIEW

**Comment by everett-hayes** [comment]
cc @yawkat

**Comment by everett-hayes** [comment]
I can't seem to add reviewers to the PR 🤔. The pipeline also seems to not be running after signing the CLA. Have I done anything else wrong?

File: http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java [hunk 1]
```diff
@@ -227,25 +227,25 @@ public class DefaultHttpClient implements
...
-     * <p>
-     * Stored as a {@link HttpHeaders} with empty values because presumably someone thought about optimizing those
-     * already.
+     * When following a 307 or 308 redirect, body related headers should be kept. Standard hop-by-hop
+     * and host-specific headers are still dropped.
      */
-    private static final HttpHeaders REDIRECT_HEADER_BLOCKLIST;
+    private static final HttpHeaders REDIRECT_HEADER_BLOCKLIST_PRESERVE_BODY = new DefaultHttpHeaders()
+        .add(HttpHeaderNames.HOST, "")
+        .add(HttpHeaderNames.TRANSFER_ENCODING, "")
```
Comment (yawkat) [inline http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java]:
```suggestion
```

Transfer encoding should also stay, probably

**Comment by yawkat** [comment]
Thanks!
