### PR TITLE
Fix stream backpressure when compressing

### LINKED ISSUE #11114: Micronaut 4.6.x: Static resources loading is broken
Look to this issue to get example: https://github.com/micronaut-projects/micronaut-openapi/issues/1728

I compared versions 4.5.4 and 4.6.3. This is what I see in the logs:

`v4.5.4`:
```
17:20:19.607 DEBUG [default-nioEventLoopGroup-1-5] i.m.h.s.n.NettyRequestLifecycle [NettyRequestLifecycle.java:75] - Request GET /swagger-ui/res/swagger-ui.css
17:20:19.608 TRACE [default-nioEventLoopGroup-1-5] i.m.h.s.cors.CorsFilter [CorsFilter.java:100] - Http Header Origin not present. Proceeding with the request.
17:20:19.608 TRACE [default-nioEventLoopGroup-1-5] i.m.h.s.cors.CorsFilter [CorsFilter.java:100] - Http Header Origin not present. Proceeding with the request.
17:20:19.612 DEBUG [default-nioEventLoopGroup-1-5] i.m.c.e.ApplicationEventPublisher [ApplicationEventPublisherFactory.java:224] - Publishing event: io.micronaut.http.context.event.HttpRequestTerminatedEvent[source=GET /swagger-ui/res/swagger-ui.css]
17:20:19.612 TRACE [default-nioEventLoopGroup-1-5] i.m.c.e.ApplicationEventPublisher [ApplicationEventPublisherFactory.java:258] - Established event listeners [io.micronaut.runtime.http.scope.RequestCustomScope@17596e7a] for event: io.micronaut.http.context.event.HttpRequestTerminatedEvent[source=GET /swagger-ui/res/swagger-ui.css]
17:20:19.612 TRACE [default-nioEventLoopGroup-1-5] i.m.c.e.ApplicationEventPublisher [ApplicationEventPublisherFactory.java:264] - Invoking event listener [io.micronaut.runtime.http.scope.RequestCustomScope@17596e7a] for event: io.micronaut.http.context.event.HttpRequestTerminatedEvent[source=GET /swagger-ui/res/swagger-ui.css]
```
изображение

`v4.6.3`:
```
17:23:50.402 DEBUG [default-nioEventLoopGroup-1-5] i.m.h.s.n.NettyRequestLifecycle [NettyRequestLifecycle.java:72] - Request GET /swagger-ui/res/swagger-ui.css
17:23:50.402 TRACE [default-nioEventLoopGroup-1-5] i.m.h.s.RequestLifecycle [RequestLifecycle.java:400] - Not matched route for request GET - /swagger-ui/res/swagger-ui.css
17:23:50.402 TRACE [default-nioEventLoopGroup-1-5] i.m.h.s.cors.CorsFilter [CorsFilter.java:100] - Http Header Origin not present. Proceeding with the request.
17:23:50.402 TRACE [default-nioEventLoopGroup-1-5] i.m.h.s.cors.CorsFilter [CorsFilter.java:100] - Http Header Origin not present. Proceeding with the request.
```
изображение

### Version

4.6.3

### PR DESCRIPTION
**Pull request by yawkat**
When compression is on, writeCompressing will immediately advance the buffer position, so `buf.readableBytes()` would be 0 and backpressure would not be relieved properly.

Fixes #11114

### CODE REVIEW

File: http-server-netty/src/main/java/io/micronaut/http/server/netty/body/InputStreamBodyWriter.java [hunk 1]
```diff
@@ -58,6 +59,7 @@ public final class InputStreamBodyWriter extends AbstractFileBodyWriter implemen
 
     @Override
     public void writeTo(HttpRequest<?> request, MutableHttpResponse<InputStream> outgoingResponse, Argument<InputStream> type, MediaType mediaType, InputStream object, NettyWriteContext nettyContext) throws CodecException {
+        outgoingResponse.getHeaders().setIfMissing(HttpHeaderNames.CONTENT_TYPE, mediaType);
```
Comment (dstepanov) [inline http-server-netty/src/main/java/io/micronaut/http/server/netty/body/InputStreamBodyWriter.java:62]: Check if mediaType is not null

**Review by dstepanov — APPROVED** [review]
