### PR TITLE
Fix ordering of bean event listeners when @Order is used and not the Ordered interface.

### LINKED ISSUE #10221: BeanEvent listener triggering order does not respect @Order
### Expected Behavior

BeanEvent listener triggering order is determined by @Order annotations and is deterministic if no default order is provided.

### Actual Behaviour

BeanEvent listener triggering order seems to be non-deterministic and it seems that @Order annotations on the event listener beans have no effect.

### Steps To Reproduce

Create multible BeanCreatedEvent implementations or the same Bean.

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.2.0

### PR DESCRIPTION
**Pull request by mikehearn**
Fixes #10221

### CODE REVIEW

**Comment by mikehearn** [comment]
The CI failure looks like it might be spurious:

```
  net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for com.google.common.base.Optional
```

File: inject/src/main/java/io/micronaut/context/DefaultBeanContext.java [hunk 1]
```diff
@@ -4157,32 +4157,47 @@ private final class EventListenerListenersSupplier<T extends EventListener> impl
...
-                    listeners.add(listener);
+                    registrations.add(registration);
+                }
+                // Avoiding the simpler Comparator.comparing(BeanRegistration::getOrder) to keep lambda setup machinery
+                // off the critical startup path.
+                registrations.sort(BeanRegistrationOrderComparator.INSTANCE);
+                for (BeanRegistration<T> registration : registrations) {
+                    listeners.add(registration.getBean());
                 }
-                OrderUtil.sort(listeners);
```
Comment (graemerocher) [inline inject/src/main/java/io/micronaut/context/DefaultBeanContext.java:4181]: unclear to me why this fix is needed. `BeanRegistration` implements `Ordered`  which intializaes the order either from the definition or the bean itself. Why is this not working?

Comment (mikehearn) [reply inject/src/main/java/io/micronaut/context/DefaultBeanContext.java:4181]: Previously OrderUtil.sort() was being called on a list of the beans themselves, not the `BeanRegistration` objects. However it's a good point that a custom comparator isn't needed in this case, so I removed that.

**Review by graemerocher — APPROVED** [review]
