### PR TITLE
Fix NPE in isCandidateBean

### LINKED ISSUE #8627: Intermittent NPE in isCandidateBean
### Expected Behavior

Should not NPE

### Actual Behaviour

NPEs with:

```
java.lang.NullPointerException: Cannot invoke "io.micronaut.inject.BeanDefinitionReference.isCandidateBean(io.micronaut.core.type.Argument)" because "this.reference" is null
      at app//io.micronaut.context.DefaultBeanContext$BeanDefinitionProducer.isReferenceCandidateBean(DefaultBeanContext.java:4187)
      at app//io.micronaut.context.DefaultBeanContext.collectBeanCandidates(DefaultBeanContext.java:2183)
      at app//io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2161)
      a
```

Broken in this commit https://github.com/micronaut-projects/micronaut-core/commit/6b8fa8a693a2c311663319734bea80c2ec9ab846

### Steps To Reproduce

Run tests in Micronaut Serialization or core

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.0.x

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes #8627

### CODE REVIEW

**Review by yawkat — APPROVED** [review]

**Review by sdelamo — COMMENTED** [review]
can we add a test?

**Review by graemerocher — APPROVED** [review]

File: inject/src/main/java/io/micronaut/context/DefaultBeanContext.java [hunk 1]
```diff
@@ -4163,31 +4169,40 @@ public boolean isDefinitionEnabled(DefaultBeanContext context, @Nullable BeanRes
         }
 
         public <T> BeanDefinitionReference<T> getReference() {
-            if (reference == null || referenceEnabled == null || !referenceEnabled) {
+            // The reference needs to be assigned to a new variable as it can change between checks
+            Boolean refEnabled = referenceEnabled;
+            if (reference == null || refEnabled == null || !refEnabled) {
```
Comment (sdelamo) [inline inject/src/main/java/io/micronaut/context/DefaultBeanContext.java:4174]: should we also do   

`BeanDefinitionReference<?> ref = reference;`?

Comment (dstepanov) [reply inject/src/main/java/io/micronaut/context/DefaultBeanContext.java:4174]: It's only problematic when you read it twice: first null check then compare value, the second check might cause the NPE.
