### PR TITLE
Use bean property writer type as the property type. Correct annotations creation for fields.

### LINKED ISSUE #8213: Can't read class level annotations when read beanProperties with micronaut 4.0.0 (micronaut-openapi)
### Expected Behavior

All tests must be passed.

### Actual Behaviour

Now all test, which read class level annotation are failed.

### Steps To Reproduce

1. Get PR https://github.com/micronaut-projects/micronaut-openapi/pull/831
2. Run tests `OpenApiSchemaFieldSpec`
изображение
изображение

As I understand, problem with annotation metadata, when you try to get by chain like this:
```java
PropertyElement publicField = classElement.getBeanProperties().get(0)
publicField.getType().getAnnotationNames()  // <----- here is empty list
```

Now all tests with class level annotation failed.

### Environment Information

 - JDK17

### Example Application

_No response_

### Version

4.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes #8213

### CODE REVIEW

File: inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java [hunk 1]
```diff
@@ -215,7 +215,7 @@ public AnnotationMetadata buildDeclared(T element, List<? extends A> annotations
      * @return The {@link AnnotationMetadata}
      */
     public CachedAnnotationMetadata lookupOrBuildForParameter(T owningType, T methodElement, T parameterElement) {
-        return lookupOrBuild(true, owningType, methodElement, parameterElement);
+        return lookupOrBuild(false, owningType, methodElement, parameterElement);
```
Comment (dstepanov) [inline inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java:218]: The correct value is false. It isn't implemented for parameters anyway. That's why `true` didn't do anything.

File: inject/src/main/java/io/micronaut/inject/ast/utils/AstBeanPropertiesUtils.java [hunk 2]
```diff
@@ -327,14 +323,11 @@ private static boolean canMethodBeUsedForAccess(MethodElement methodElement,
...
-            case PUBLIC:
-                return memberElement.isPublic();
-            default:
-                return false;
-        }
+        return switch (visibility) {
+            case DEFAULT ->
+                !memberElement.isPrivate() && (memberElement.isAccessible() || memberElement.getDeclaringType().hasDeclaredStereotype(BeanProperties.class));
+            case PUBLIC -> memberElement.isPublic();
+        };
```
Comment (graemerocher) [inline inject/src/main/java/io/micronaut/inject/ast/utils/AstBeanPropertiesUtils.java:330]: Switch expressions 😍

**Review by graemerocher — APPROVED** [review]
