### PR TITLE
Validate nullable is not used on primite parameters. Fixes #3666

### LINKED ISSUE #3666: Validate executable methods with primitive arguments with @Nullable
Adding `@Nullable` to a primitive argument allows Micronaut's generated code to pass a null value, which will fail at runtime. We can catch this error at compile time instead. This would apply to all executable methods

### PR DESCRIPTION
**Pull request by ilopmar**
Some comments:

- I needed to declare the TypeElementVisitor as `TypeElementVisitor<Object, Object>`. If I do `TypeElementVisitor<Object, Executable>` it will work for `@Controller` for not for `@Singleton`, because a `@Singleton` class is not `@Executable`.
- I've also tried with the declarative HTTP Client and the methods there are not being validated. Probably because TypeElemenVisitors only work for classes and not interfaces, right? Is there anything we can do this case?

### CODE REVIEW

File: validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+import io.micronaut.inject.visitor.VisitorContext;
+
+/**
+ * A {@link io.micronaut.inject.visitor.TypeElementVisitor} that validates primitive types can't have a Nullable annotation.
+ *
+ * @author Iván López
+ * @since 2.0.1
+ */
+@Internal
+public class ExecutableVisitor implements TypeElementVisitor<Object, Object> {
```
Comment (graemerocher) [inline validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java:31]: Should declare isolating:

```
    @NonNull
    @Override
    public VisitorKind getVisitorKind() {
        return VisitorKind.ISOLATING;
    }
```

**Comment by jameskleeh** [comment]
@ilopmar Regarding clients, I don't think that is a concern because the user executes the method and not us

**Comment by ilopmar** [comment]
So, this change has detected some places in which where using `@Nullable` with `int` :rofl: https://github.com/micronaut-projects/micronaut-core/blob/13c0e2990e55ef9bf068b8a596ddda758807683c/http-client/src/test/groovy/io/micronaut/http/client/aop/StreamSpec.groovy#L169

I'll fix them!

**Comment by ilopmar** [comment]
Changes done and build is green now. Ready to review.

File: validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+
+    @NonNull
+    @Override
+    public VisitorKind getVisitorKind() {
+        return VisitorKind.ISOLATING;
+    }
+
+    @Override
+    public void visitMethod(MethodElement element, VisitorContext context) {
+        ParameterElement[] parameters = element.getParameters();
```
Comment (jameskleeh) [inline validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java:42]: We need to ensure the `MethodElement` is annotated with `@Executable`. Can you look into why `TypeElementVisitor<Object, Executable>` is not working?

File: validation/src/test/groovy/io/micronaut/validation/executable/NullablePrimitiveSpec.groovy [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+    String errorMsg = "Primitive types can not be null"
+
+    void 'test @Nullable is not allowed on primitive parameters'() {
+        when:
+        buildTypeElement("""
+package test;
+
+@javax.inject.Singleton
+class Foo {
+    void bar(@javax.annotation.Nullable boolean boolPrimitive) {
```
Comment (jameskleeh) [inline validation/src/test/groovy/io/micronaut/validation/executable/NullablePrimitiveSpec.groovy:18]: This type of scenario should still compile because Micronaut will not be executing this method

File: validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java (hunk 2 above)
Comment (graemerocher) [reply validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java:42]: If we can limit this as much as possible to a pair of meta annotations it is better for incremental compilation

File: validation/src/test/groovy/io/micronaut/validation/executable/NullablePrimitiveSpec.groovy (hunk 3 above)
Comment (ilopmar) [reply validation/src/test/groovy/io/micronaut/validation/executable/NullablePrimitiveSpec.groovy:18]: I'm sorry James, you are right. I was confused at the beginning and didn't really think about the difference on "user calling it's own code" vs "Micronaut calling user code" (like in a controller). It's fixed now.

File: validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java (hunk 2 above)
Comment (ilopmar) [reply validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java:43]: @jameskleeh fixed now. See my comment: https://github.com/micronaut-projects/micronaut-core/pull/3698#discussion_r452714413 and https://github.com/micronaut-projects/micronaut-core/pull/3698/commits/5197f8a986e7d5bb34fd73ce5e679ee4fb8465d5.

@graemerocher Can you please explain what do you mean? I've pushed a commit that makes it work with `TypeElementVisitor<Object, Executable>`. Do you mean making it for something that it's not `Object`? Like  `TypeElementVisitor<Any-other-thing-here, Executable>?

Comment (graemerocher) [reply validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java:43]: If you have been able to limit it to just `@Executable` that is probably ok. In general `<Object, Object>` is bad for incremental compilation since it has to visit every annotation which breaks the way Gradle's incremental compilation works. Currently this is only a problem with `GraalTypeElementVisitor` I believe, which is the only one that visits everything (really we should try and change that visitor or restructure it to visit fewer annotations)

Comment (ilopmar) [reply validation/src/main/java/io/micronaut/validation/executable/ExecutableVisitor.java:43]: Thanks for the clarification.

Regarding the `GraalTypeElementVisitor`, if you have any idea or guidance in mind, please open an issue explaining what you have in mind and I can give it a try.

**Comment by ilopmar** [comment]
I've updated the branch with the latest changes from master. I think then we can merge it, right?
