### PR TITLE
Fix the Hateoas/Groovy/Serde error in a binary compatible way

### LINKED ISSUE #8184: ErrorResponseProcessor in a Groovy project throws CNF exception
### Expected Behavior

Given a custom exception `WhoopsException`, I should be able to create an `ExceptionHandler` which processes a response for this via `ErrorResponseProcessor`, ie:

```
@Produces
@Singleton
class MyExceptionHandler implements ExceptionHandler<WhoopsException, HttpResponse<?>>{

    private final ErrorResponseProcessor<?> errorResponseProcessor

    MyExceptionHandler(ErrorResponseProcessor<?> errorResponseProcessor) {
        this.errorResponseProcessor = errorResponseProcessor
    }

    @Override
    HttpResponse<?> handle(HttpRequest request, WhoopsException exception) {
        ErrorContext errorContext = ErrorContext.builder(request)
                .cause(exception)
                .errorMessage(exception.getMessage())
                .build()
        errorResponseProcessor.processResponse(errorContext, unprocessableEntity())
    }
}
```

### Actual Behaviour

However, when it attempts to call `processResponse`, it fails with

```
java.lang.NoClassDefFoundError: io/micronaut/jackson/JacksonConfiguration
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2357)
	at org.codehaus.groovy.reflection.CachedClass$2.lambda$initValue$4(CachedClass.java:71)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:76)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:50)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:37)
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:259)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:223)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:233)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:166)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:156)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:139)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:272)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:315)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:325)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:262)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:983)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createPojoSite(CallSiteArray.java:116)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:160)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at com.example.MyExceptionHandler.handle(MyExceptionHandler.groovy:29)
```

I suspect Groovy is trying to find JacksonConfiguration when it tries to load the `HateoasErrorResponseProcessor`

### Steps To Reproduce

1. Clone linked project
2. Run project
3. curl http://localhost:8080

### Environment Information

_No response_

### Example Application

https://github.com/bloidonia/serde-groovy-issue

### Version

3.7.1

### PR DESCRIPTION
**Pull request by timyates**
When trying to use Groovy and Serde and the default ErrorProcessor, Groovy throws a ClassNotFound exception.

This fix adds a replacement for the HateoasErrorResponseProcessor that (if groovy-runtime is on the classpath) doesn't use JacksonConfiguration.

It also deprecates the JacksonConfiguration constructor for removal in 4.0.0

Fixes #8184

### CODE REVIEW

**Review by yawkat — APPROVED** [review]

File: http-server/src/main/java/io/micronaut/http/server/exceptions/response/HateoasErrorResponseProcessorReplacement.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+import jakarta.inject.Singleton;
+
+/**
+ * @deprecated Replacement is no longer necessary for Micronaut Framework 4.0 since {@link io.micronaut.http.server.exceptions.response.HateoasErrorResponseProcessor} jackson constructor will be removed.
+ * @author Tim Yates
+ * @since 3.7.3
+ */
+@Deprecated
+@Singleton
+@Requires(classes = GroovyPropertySourceLoader.class)
```
Comment (sdelamo) [inline http-server/src/main/java/io/micronaut/http/server/exceptions/response/HateoasErrorResponseProcessorReplacement.java:34]: should we add an additional @Requires if serde jackson is present?

Comment (timyates) [reply http-server/src/main/java/io/micronaut/http/server/exceptions/response/HateoasErrorResponseProcessorReplacement.java:34]: Do you think it's worth it?  This will work whether it's there or not, and it would be another compileOnly jar on the classpath 🤔

**Review by sdelamo — APPROVED** [review]
