### PR TITLE
Reset shared `ConversionService` instance state on context restart

### LINKED ISSUE #237: 3.5.0 regression: Unexpected error occurred: Error instantiating bean of type  [io.micronaut.serde.config.SerdeConfiguration$Intercepted]
### Expected Behavior

Expect tests to pass. If you clone branch `master` which uses Micronaut 3.4.4, it works. 

### Actual Behaviour

A single tests works:

```
./gradlew test --tests "com.objectcomputing.todo.controller.TodoControllerTest"
```
The tests in package fail

```
% ./gradlew test --tests "com.objectcomputing.todo.controller.*" --stacktrace

> Task :test

TodoControllerTest > getTodoRetrievesEveryTodoOfAUser() FAILED
    io.micronaut.http.client.exceptions.HttpClientResponseException at DefaultHttpClient.java:3317
```

Standard output

```
.125?[0;39m ?[1;30m[default-nioEventLoopGroup-3-5]?[0;39m ?[1;31mERROR?[0;39m ?[35mi.m.http.server.RouteExecutor?[0;39m - Unexpected error occurred: Error instantiating bean of type  [io.micronaut.serde.config.SerdeConfiguration$Intercepted]

Message: Bean of type [class io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment] is a manually registered singleton that was registered with the context via BeanContext.registerBean(..) and cannot be created directly
Path Taken: new JacksonJsonMapper(SerdeRegistry registry) --> new JacksonJsonMapper([SerdeRegistry registry]) --> new DefaultSerdeRegistry(BeanContext beanContext,[ObjectSerializer objectSerializer],ObjectDeserializer objectDeserializer,Serde objectArraySerde,SerdeIntrospections introspections) --> new ObjectSerializer([SerdeIntrospections introspections],SerializationConfiguration configuration) --> new DefaultSerdeIntrospections([SerdeConfiguration configuration]) --> new SerdeConfiguration$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,[List $interceptors])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.serde.config.SerdeConfiguration$Intercepted]

Message: Bean of type [class io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment] is a manually registered singleton that was registered with the context via BeanContext.registerBean(..) and cannot be created directly
Path Taken: new JacksonJsonMapper(SerdeRegistry registry) --> new JacksonJsonMapper([SerdeRegistry registry]) --> new DefaultSerdeRegistry(BeanContext beanContext,[ObjectSerializer objectSerializer],ObjectDeserializer objectDeserializer,Serde objectArraySerde,SerdeIntrospections introspections) --> new ObjectSerializer([SerdeIntrospections introspections],SerializationConfiguration configuration) --> new DefaultSerdeIntrospections([SerdeConfiguration configuration]) --> new SerdeConfiguration$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,[List $interceptors])
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2346)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2284)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2230)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:2995)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2885)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2832)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3490)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3436)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3410)
	at io.micronaut.context.AbstractBeanResolutionContext.getBeanRegistrations(AbstractBeanResolutionContext.java:96)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBeanRegistrations(AbstractInitializableBeanDefinition.java:2194)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanRegistrationsForConstructorArgument(AbstractInitializableBeanDefinition.java:1464)
	at io.micronaut.serde.config.$SerdeConfiguration$Intercepted$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2333)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2284)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2230)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:2995)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2897)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2858)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2779)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1596)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2069)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1299)
	at io.micronaut.serde.support.$DefaultSerdeIntrospections$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2333)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2284)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2230)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:2995)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2897)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2858)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2779)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1596)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2069)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1299)
	at io.micronaut.serde.support.serializers.$ObjectSerializer$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2333)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2284)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2230)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:2995)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2897)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2858)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2779)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1596)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2069)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1299)
	at io.micronaut.serde.support.$DefaultSerdeRegistry$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2333)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2284)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2230)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:2995)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2897)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2858)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2779)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1596)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2069)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1299)
	at io.micronaut.serde.jackson.$JacksonJsonMapper$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2333)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2284)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2230)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:2995)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2897)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2858)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2779)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1596)
	at io.micronaut.inject.provider.BeanProviderDefinition$1.get(BeanProviderDefinition.java:81)
	at io.micronaut.json.convert.JsonConverterRegistrar.lambda$jsonNodeToObjectConverter$5(JsonConverterRegistrar.java:238)
	at io.micronaut.core.convert.DefaultConversionService.convert(DefaultConversionService.java:140)
	at io.micronaut.context.env.DefaultEnvironment.convert(DefaultEnvironment.java:305)
	at io.micronaut.core.convert.ConversionService.convert(ConversionService.java:117)
	at io.micronaut.http.bind.binders.DefaultBodyAnnotationBinder.bind(DefaultBodyAnnotationBinder.java:78)
	at io.micronaut.http.bind.binders.DefaultBodyAnnotationBinder.bind(DefaultBodyAnnotationBinder.java:37)
	at io.micronaut.http.server.binding.RequestArgumentSatisfier.lambda$getValueForBlockingBodyArgumentBinder$4(RequestArgumentSatisfier.java:168)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:265)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:172)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$4.doOnComplete(RoutingInBoundHandler.java:953)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:79)
	at io.micronaut.http.server.netty.jackson.JsonContentProcessor$1.doOnComplete(JsonContentProcessor.java:136)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:79)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.micronaut.core.async.processor.SingleThreadedBufferingProcessor.doOnComplete(SingleThreadedBufferingProcessor.java:48)
	at io.micronaut.jackson.core.parser.JacksonCoreProcessor.doOnComplete(JacksonCoreProcessor.java:94)
	at io.micronaut.core.async.subscriber.SingleThreadedBufferingSubscriber.onComplete(SingleThreadedBufferingSubscriber.java:71)
	at io.micronaut.http.server.netty.jackson.JsonContentProcessor.doOnComplete(JsonContentProcessor.java:161)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:79)
	at io.micronaut.http.netty.reactive.HandlerPublisher.publishMessage(HandlerPublisher.java:383)
	at io.micronaut.http.netty.reactive.HandlerPublisher.flushBuffer(HandlerPublisher.java:470)
	at io.micronaut.http.netty.reactive.HandlerPublisher.publishMessageLater(HandlerPublisher.java:360)
	at io.micronaut.http.netty.reactive.HandlerPublisher.complete(HandlerPublisher.java:423)
	at io.micronaut.http.netty.reactive.HandlerPublisher.handlerRemoved(HandlerPublisher.java:418)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:483)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:319)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:282)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:134)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
	at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:139)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671)
	at io.micronaut.http.netty.reactive.HandlerPublisher.requestDemand(HandlerPublisher.java:165)
	at io.micronaut.http.netty.stream.HttpStreamsHandler$2.requestDemand(HttpStreamsHandler.java:273)
	at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.receivedDemand(HandlerPublisher.java:556)
	at io.micronaut.http.netty.reactive.HandlerPublisher$ChannelSubscription.lambda$request$0(HandlerPublisher.java:494)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsupportedOperationException: Bean of type [class io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment] is a manually registered singleton that was registered with the context via BeanContext.registerBean(..) and cannot be created directly
	at io.micronaut.context.NoInjectionBeanDefinition.getConstructor(NoInjectionBeanDefinition.java:131)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanDefinition(DefaultBeanContext.java:2294)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2286)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2230)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:2995)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2897)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2858)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2779)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1596)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2069)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1299)
	at io.micronaut.runtime.context.env.$ConfigurationIntroductionAdvice$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2333)
	... 151 common frames omitted
```

### Steps To Reproduce

Clone `update` branch of https://github.com/sdelamo/micronaut-todo-spa

https://github.com/sdelamo/micronaut-todo-spa/tree/update

### Environment Information

JDK 11

MacOS Monterey

### Example Application

https://github.com/sdelamo/micronaut-todo-spa

### Version

3.5.2

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes https://github.com/micronaut-projects/micronaut-serialization/issues/237

### CODE REVIEW

**Comment by graemerocher** [comment]
can you fix the test failures? Seem tests relied on this previously present shared state.

**Comment by dstepanov** [comment]
Targeting 3.6

File: core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java [hunk 1]
```diff
@@ -924,6 +957,16 @@ protected void registerDefaultConverters() {
                 new MultiValuesConverterFactory.MapToMultiValuesConverter(this));
         addConverter(Object.class, io.micronaut.core.convert.value.ConvertibleMultiValues.class,
                 new MultiValuesConverterFactory.ObjectToMultiValuesConverter(this));
+
+        Collection<TypeConverterRegistrar> registrars = new ArrayList<>();
+        ForkJoinPool forkJoinPool = new ForkJoinPool(); // Create a custom ForkJoinPool to prevent deadlock
```
Comment (yawkat) [inline core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java]: could also use `SoftServiceLoader.disableFork` instead

File: core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java [hunk 2]
```diff
@@ -924,6 +957,16 @@ protected void registerDefaultConverters() {
...
+        SoftServiceLoader.load(TypeConverterRegistrar.class)
+            .withForkJoinPool(forkJoinPool)
+            .collectAll(registrars);
+        for (TypeConverterRegistrar registrar : registrars) {
+            registrar.register(this);
+        }
+        forkJoinPool.shutdown();
```
Comment (yawkat) [inline core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java]: move into finally

File: core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java (hunk 1 above)
Comment (yawkat) [reply core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java]: this would also remove the need for the SoftServiceLoader changes below (though it could impact performance)

File: http-netty/src/test/groovy/io/micronaut/http/netty/allocator/DefaultAllocatorSpec.groovy [hunk 3]
```diff
@@ -37,6 +38,7 @@ class DefaultAllocatorSpec extends Specification {
         'maxCachedByteBuffersPerChunk' | 20
     }
 
+    @Ignore
```
Comment (yawkat) [inline http-netty/src/test/groovy/io/micronaut/http/netty/allocator/DefaultAllocatorSpec.groovy]: if this reliably fails now, maybe your change caused the allocator class that reads the system property to load before the config is applied. this needs to be fixed

**Comment by yawkat** [comment]
can you explain why this change is necessary and related to the serialization issue? what kind of state is the shared conversion context carrying that needs to be reset?

File: core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java (hunk 1 above)
Comment (dstepanov) [reply core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java]: I'm afraid it's going to be the first touch of the jars filesystem and it will cause a slowdown.

Comment (yawkat) [reply core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java]: should definitely measure this, creating an entirely new fjp will have overhead from starting all the threads, too

**Comment by dstepanov** [comment]
We register convertors into the static instance which is shared across bean contexts. The problem arises when the convertor was registered with an instance of the bean context, that convertor will fail when accessed after the bean context is destroyed.

**Comment by yawkat** [comment]
ah, makes sense. a bit weird though to register to a shared conversion context from a bean context that isnt shared...

**Comment by dstepanov** [comment]
We should change it probably in 4.0. Shared `ConversionService` to allow contribute converters only using service loaded and another bean context instance `ConversionService` delegating to the static one. I have something like this in Micronaut Data.

**Comment by dstepanov** [comment]
It looks like custom `ForkAndJoin` still deadlocks

**Comment by yawkat** [comment]
is it called in a static initializer? in that case you cant use multithreading at all without risking deadlocks

**Comment by dstepanov** [comment]
Yep, going to remove forking

**Review by yawkat — APPROVED** [review]

**Comment by graemerocher** [comment]
Still failing on Java 17 :(

**Comment by dstepanov** [comment]
I did restart and it passed :-/

**Review by sdelamo — APPROVED** [review]
