### PR TITLE
fix: avoid containsBean cache race during concurrent cache clears

### LINKED ISSUE #11768: NPE in DefaultBeanContext.containsBean
### Expected Behavior

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null
        at io.micronaut.context.DefaultBeanContext.containsBean(DefaultBeanContext.java:826)
        at io.micronaut.context.DefaultBeanContext.containsBean(DefaultBeanContext.java:818)
        at io.micronaut.context.BeanDefinitionRegistry.containsBean(BeanDefinitionRegistry.java:676)
        at io.micronaut.context.conditions.MatchesPresenceOfBeansCondition.matches(MatchesPresenceOfBeansCondition.java:45)
        at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:139)
        at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:108)
        at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:48)
        at io.micronaut.context.DefaultApplicationContext.createAndAddDelegate(DefaultApplicationContext.java:667)
        at io.micronaut.context.DefaultApplicationContext.transformEachBeanBeanDefinition(DefaultApplicationContext.java:585)
        at io.micronaut.context.DefaultApplicationContext.collectIterableBeans(DefaultApplicationContext.java:486)
        at io.micronaut.context.DefaultBeanContext.collectBeanCandidates(DefaultBeanContext.java:2204)
        at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:2173)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3208)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3192)
        at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:2779)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2748)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1842)
        at io.micronaut.context.BeanDefinitionDelegate.getParametersValues(BeanDefinitionDelegate.java:228)
        at io.micronaut.context.BeanDefinitionDelegate.instantiate(BeanDefinitionDelegate.java:166)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2335)
        ... 86 common frames omitted
```

Easy to fix, but I have a dirty tree right now so I will check later.

### Actual Behaviour

_No response_

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.9

### PR DESCRIPTION
**Pull request by yawkat**
## Summary
- replace `containsBeanCache.containsKey(...)` + `get(...)` with an atomic `get`-first path in `DefaultBeanContext.containsBean` to avoid a race where concurrent cache clears can lead to a null-unboxing NPE
- add a regression test that stresses concurrent `containsBean` lookups with cache clears to reproduce the race on old code and verify the fix
- validate with targeted and full `:micronaut-inject:test` runs on JDK 21

Fixes #11768

### CODE REVIEW

File: inject/src/main/java/io/micronaut/context/DefaultBeanContext.java [hunk 1]
```diff
@@ -183,7 +183,7 @@ public boolean test(BeanDefinition<?> candidate) {
     private final Map<String, List<String>> disabledConfigurations = new ConcurrentHashMap<>(5);
     private final Map<String, BeanConfiguration> beanConfigurations = new HashMap<>(10);
 
-    private final Map<BeanKey, Boolean> containsBeanCache = new ConcurrentHashMap<>(30);
+    final Map<BeanKey, Boolean> containsBeanCache = new ConcurrentHashMap<>(30);
```
Comment (graemerocher) [inline inject/src/main/java/io/micronaut/context/DefaultBeanContext.java:186]: can we avoid making this package private?

**Review by graemerocher — APPROVED** [review]

File: inject/src/main/java/io/micronaut/context/DefaultBeanContext.java (hunk 1 above)
Comment (yawkat) [reply inject/src/main/java/io/micronaut/context/DefaultBeanContext.java:186]: The AI actually tried to get reflection to do access before :sweat_smile: 

I think this approach is better than trying to trigger cache clearing from elsewhere, this way the bug reproduces more easily.
