### PR TITLE
Issue 4306 - Bean validation should fail if @Valid field is not introspected

### LINKED ISSUE #4306: Bean validation should fail if @Valid field is not introspected
2.1.0

If you are using `@Valid` on the body parameter there is a runtime error if the field type is not `@Introspected` (BTW: It would be great have compile-time error but I guess that wouldn't be correct for Hibernate validator)
That is not the case if you have a nested field with a type without introspection, the field is not validated and you are wondering was is wrong.

### PR DESCRIPTION
**Pull request by wetted**
Issue 4306 - Bean validation should fail if @Valid field is not introspected
- emit validation failure when `@Valid` alone is applied to a container of elements where the element type is not `@Introspected`.
- this does not address cases with additional constraint(s), since that might still be legal if the element type is supported by those constraints directly (e.g. `@Valid @Size(min=1, max=2) List<String> strs`), even though something like `@Valid @Size(min=1, max=2) List<NotIntrospected> oops` might be bogus.

### CODE REVIEW

File: validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java [hunk 1]
```diff
@@ -1331,6 +1320,14 @@ public void keyedValue(String nodeName, Object key, Object keyedValue) {
             @Nullable DefaultPropertyNode container) {
 
         final BeanIntrospection<Object> beanIntrospection = getBeanIntrospection(propertyValue);
+        AnnotationMetadata annotationMetadata = cascadeProperty.getAnnotationMetadata();
+        if (beanIntrospection == null && annotationMetadata.getDeclaredAnnotationNames().equals(
```
Comment (jameskleeh) [inline validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java]: `@Valid` is not annotated with `@Constraint` so you can just look for the presence of that annotation instead of comparing the annotation names
