### PR TITLE
Fix for method argument annotation visitors.

### LINKED ISSUE #4008: Method argument annotations from processor not working
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. See https://github.com/tomas-langer/reproduce-micronaut-visitor

### Expected Behaviour

When I have a `TypeElementVisitor` implemented that adds an annotation to a method parameter, that annotation should be visible at runtime in an executable method

The reproducer main method should successfully execute.

### Actual Behaviour

The annotation is not visible (nor is it in the generated class of the executable method).

Exception from reproducer:
```
Caused by: io.micronaut.core.bind.exceptions.UnsatisfiedArgumentException: Required argument [FirstBean paramInjection] not specified
	at io.micronaut.core.bind.DefaultExecutableBinder.bind(DefaultExecutableBinder.java:96)
	at io.reproducers.reproducer.impl.ExecMethodProcessor.process(ExecMethodProcessor.java:37)
	at io.reproducers.reproducer.impl.ExecMethodProcessor.process(ExecMethodProcessor.java:17)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:89)
	... 10 more
```

### Environment Information

- **Operating System**: MacOS 
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11

### Example Application

https://github.com/tomas-langer/reproduce-micronaut-visitor

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #4008 

This fix makes sure the updated annotation metadata is stored in the modified cache under the same key it is retrieved later on.

This PR also includes a test verifying the annotation is correctly added.

### CODE REVIEW

**Review by jameskleeh — APPROVED** [review]
Thanks for the PR!

File: inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java [hunk 1]
```diff
@@ -76,7 +77,20 @@
                 .newAnnotationBuilder()
                 .annotate(annotationMetadata, av);
 
-        String declaringTypeName = this instanceof MemberElement ? ((MemberElement) this).getOwningType().getName() : getName();
+        String declaringTypeName;
+        if (this instanceof MemberElement) {
+            declaringTypeName = ((MemberElement) this).getOwningType().getName();
+        } else if (this instanceof ParameterElement) {
+            TypeElement typeElement = visitorContext.getModelUtils().classElementFor((Element) this.getNativeType());
```
Comment (tomas-langer) [inline inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java:84]: The only part I am not sure about is if this cast is safe, or if there is another way to obtain the declaring type...

Comment (graemerocher) [reply inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java:84]: Yes it is safe
